# academic-advisor-backend/scripts/seed_career_data.py
import asyncio
import logging
from app.models.career import (
    CareerPath,
    CareerCategory,
    DemandLevel,
    SalaryRange,
    RoadmapStep,
)

logger = logging.getLogger(__name__)

CAREERS = [
    # ─── 1 Software Developer ───────────────────────────
    CareerPath(
        title="Software Developer",
        category=CareerCategory.SOFTWARE_DEVELOPMENT,
        description="Design, develop, and maintain software applications. Full lifecycle involvement from requirements to deployment. One of the most in-demand roles in the Indian IT industry.",
        required_skills=["Python", "Java", "JavaScript", "Data Structures", "Algorithms", "Git", "SQL", "REST APIs", "System Design"],
        recommended_subjects=["Data Structures and Algorithms", "Software Engineering", "Database Management Systems", "Operating Systems"],
        recommended_electives=["Cloud Computing Services", "Software Testing"],
        min_cgpa_recommended=6.5,
        job_titles=["Software Engineer", "SDE-1", "SDE-2", "Application Developer", "Backend Developer"],
        salary_range=SalaryRange(entry_level="4-8 LPA", mid_level="10-20 LPA", senior_level="20-40 LPA", top_companies="25-60+ LPA"),
        top_companies_india=["TCS", "Infosys", "Wipro", "HCL", "Cognizant", "Flipkart", "Razorpay", "PhonePe", "Juspay"],
        top_companies_global=["Google", "Microsoft", "Amazon", "Meta", "Apple"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — constant demand across all industries",
        certifications=["AWS Certified Developer", "Oracle Java Certification", "Microsoft Azure Developer"],
        roadmap=[
            RoadmapStep(step=1, title="Master DSA & OOP", description="Solve 200+ problems on LeetCode/GFG", duration="3-4 months"),
            RoadmapStep(step=2, title="Learn a Framework", description="Spring Boot (Java) or Django/FastAPI (Python) or Node.js", duration="2-3 months"),
            RoadmapStep(step=3, title="Build Projects", description="Build 2-3 full-stack projects with real-world features", duration="3-4 months"),
            RoadmapStep(step=4, title="System Design Basics", description="Study scalability, load balancing, caching, databases", duration="2 months"),
            RoadmapStep(step=5, title="Apply & Interview", description="Target product companies via campus/off-campus drives", duration="Ongoing"),
        ],
        keywords=["software", "developer", "engineer", "coding", "programming", "sde", "backend", "fullstack"],
        related_careers=["Full Stack Developer", "DevOps Engineer", "Cloud Architect"],
    ),
    # ─── 2 Data Scientist ───────────────────────────────
    CareerPath(
        title="Data Scientist",
        category=CareerCategory.DATA_AND_AI,
        description="Extract insights from complex data using statistics, machine learning, and domain expertise. High-paying role with growing demand in India's analytics industry.",
        required_skills=["Python", "Statistics", "Machine Learning", "SQL", "Pandas", "NumPy", "Scikit-learn", "Data Visualization", "Deep Learning"],
        recommended_subjects=["Engineering Mathematics-III", "Engineering Mathematics-IV", "Python Programming", "Database Management Systems"],
        recommended_electives=["Machine Learning", "Big Data Analytics", "Data Warehouse and Mining"],
        min_cgpa_recommended=7.0,
        job_titles=["Data Scientist", "ML Engineer", "Data Analyst", "Research Scientist", "Applied Scientist"],
        salary_range=SalaryRange(entry_level="6-12 LPA", mid_level="12-25 LPA", senior_level="25-50 LPA", top_companies="30-70+ LPA"),
        top_companies_india=["Flipkart", "Amazon India", "Mu Sigma", "Fractal Analytics", "Tiger Analytics", "Paytm", "PhonePe"],
        top_companies_global=["Google", "Meta", "Netflix", "Apple", "OpenAI"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — data-driven decision making is transforming every industry",
        certifications=["Google Data Analytics Certificate", "IBM Data Science Professional", "AWS ML Specialty"],
        roadmap=[
            RoadmapStep(step=1, title="Statistics & Math", description="Master probability, linear algebra, calculus", duration="2-3 months"),
            RoadmapStep(step=2, title="Python for Data Science", description="Learn Pandas, NumPy, Matplotlib, Seaborn", duration="2 months"),
            RoadmapStep(step=3, title="Machine Learning", description="Study supervised/unsupervised algorithms, model evaluation", duration="3-4 months"),
            RoadmapStep(step=4, title="Deep Learning & NLP", description="Neural networks, CNNs, RNNs, Transformers", duration="3 months"),
            RoadmapStep(step=5, title="Kaggle & Portfolio", description="Compete on Kaggle, build end-to-end projects", duration="Ongoing"),
        ],
        keywords=["data", "scientist", "analytics", "ml", "machine learning", "ai", "statistics", "analysis"],
        related_careers=["ML Engineer", "Data Analyst", "AI Research Engineer"],
    ),
    # ─── 3 DevOps Engineer ──────────────────────────────
    CareerPath(
        title="DevOps Engineer",
        category=CareerCategory.CLOUD_AND_DEVOPS,
        description="Bridge development and operations through CI/CD pipelines, infrastructure automation, and container orchestration. Critical role in modern software delivery.",
        required_skills=["Linux", "Docker", "Kubernetes", "CI/CD", "AWS/Azure", "Terraform", "Git", "Python/Bash Scripting", "Monitoring"],
        recommended_subjects=["Operating Systems", "Computer Networks", "Software Engineering"],
        recommended_electives=["Cloud Computing Services"],
        min_cgpa_recommended=6.0,
        job_titles=["DevOps Engineer", "SRE", "Platform Engineer", "Cloud Engineer", "Release Engineer"],
        salary_range=SalaryRange(entry_level="5-10 LPA", mid_level="12-22 LPA", senior_level="22-40 LPA", top_companies="25-55+ LPA"),
        top_companies_india=["Flipkart", "Razorpay", "Dream11", "Zerodha", "Freshworks", "Zomato"],
        top_companies_global=["Google", "Amazon", "Netflix", "Spotify", "HashiCorp"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — every company needs DevOps as they scale",
        certifications=["AWS Solutions Architect", "Kubernetes CKA/CKAD", "Docker Certified Associate", "Terraform Associate"],
        roadmap=[
            RoadmapStep(step=1, title="Linux & Networking", description="Master Linux commands, networking, SSH, firewalls", duration="2 months"),
            RoadmapStep(step=2, title="Containers & Orchestration", description="Docker, Docker Compose, Kubernetes basics", duration="2-3 months"),
            RoadmapStep(step=3, title="CI/CD Pipelines", description="Jenkins, GitHub Actions, GitLab CI", duration="2 months"),
            RoadmapStep(step=4, title="Cloud Platforms", description="AWS or Azure — compute, networking, storage, IAM", duration="3 months"),
            RoadmapStep(step=5, title="IaC & Monitoring", description="Terraform, Ansible, Prometheus, Grafana", duration="2 months"),
        ],
        keywords=["devops", "cicd", "docker", "kubernetes", "cloud", "infrastructure", "deployment", "automation", "sre"],
        related_careers=["Cloud Architect", "Software Developer", "SRE"],
    ),
    # ─── 4 Cybersecurity Analyst ────────────────────────
    CareerPath(
        title="Cybersecurity Analyst",
        category=CareerCategory.SECURITY,
        description="Protect systems and networks from cyber threats. Growing rapidly in India due to digital transformation and regulatory requirements.",
        required_skills=["Network Security", "Ethical Hacking", "SIEM Tools", "Cryptography", "Linux", "Wireshark", "Penetration Testing", "Firewalls"],
        recommended_subjects=["Computer Networks", "Operating Systems", "Cryptography & Network Security"],
        recommended_electives=["Ethical Hacking", "Cyber Security"],
        min_cgpa_recommended=6.5,
        job_titles=["Security Analyst", "Penetration Tester", "SOC Analyst", "Security Engineer", "Threat Analyst"],
        salary_range=SalaryRange(entry_level="4-8 LPA", mid_level="10-20 LPA", senior_level="20-35 LPA", top_companies="25-50+ LPA"),
        top_companies_india=["Tata CISO", "Paladion", "Quick Heal", "Lucideus", "CrowdStrike India", "Palo Alto India"],
        top_companies_global=["CrowdStrike", "Palo Alto Networks", "Fortinet", "FireEye", "Deloitte Cyber"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — cybersecurity talent gap is massive globally",
        certifications=["CompTIA Security+", "CEH (Certified Ethical Hacker)", "CISSP", "OSCP"],
        roadmap=[
            RoadmapStep(step=1, title="Networking Fundamentals", description="TCP/IP, DNS, HTTP, firewalls, VPNs", duration="2 months"),
            RoadmapStep(step=2, title="Linux & Scripting", description="Linux admin, Bash/Python scripting", duration="2 months"),
            RoadmapStep(step=3, title="Security Tools", description="Wireshark, Nmap, Metasploit, Burp Suite", duration="3 months"),
            RoadmapStep(step=4, title="Certifications", description="Start with CompTIA Security+, then CEH", duration="3-6 months"),
            RoadmapStep(step=5, title="CTFs & Labs", description="Practice on HackTheBox, TryHackMe", duration="Ongoing"),
        ],
        keywords=["cybersecurity", "security", "hacking", "ethical hacking", "penetration", "infosec", "soc"],
        related_careers=["Network Engineer", "Cloud Security Engineer"],
    ),
    # ─── 5 Full Stack Developer ─────────────────────────
    CareerPath(
        title="Full Stack Developer",
        category=CareerCategory.SOFTWARE_DEVELOPMENT,
        description="Build complete web applications — frontend and backend. One of the most versatile and in-demand roles in the Indian startup ecosystem.",
        required_skills=["HTML/CSS", "JavaScript", "React/Angular/Vue", "Node.js/Python", "SQL/NoSQL", "REST APIs", "Git", "Docker"],
        recommended_subjects=["Database Management Systems", "Computer Networks", "Software Engineering", "Data Structures and Algorithms"],
        recommended_electives=["Cloud Computing Services", "Software Testing"],
        min_cgpa_recommended=6.0,
        job_titles=["Full Stack Developer", "Web Developer", "MERN Stack Developer", "Software Engineer"],
        salary_range=SalaryRange(entry_level="4-8 LPA", mid_level="10-18 LPA", senior_level="18-35 LPA", top_companies="20-50+ LPA"),
        top_companies_india=["Flipkart", "Swiggy", "CRED", "Razorpay", "Freshworks", "Zerodha", "Meesho"],
        top_companies_global=["Google", "Meta", "Shopify", "Stripe", "Vercel"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — every business needs web presence",
        certifications=["Meta Front-End Developer", "AWS Cloud Practitioner"],
        roadmap=[
            RoadmapStep(step=1, title="Frontend Basics", description="HTML, CSS, JavaScript, responsive design", duration="2-3 months"),
            RoadmapStep(step=2, title="Frontend Framework", description="React.js or Angular — build SPAs", duration="2-3 months"),
            RoadmapStep(step=3, title="Backend Development", description="Node.js + Express or Python + FastAPI", duration="2-3 months"),
            RoadmapStep(step=4, title="Database & APIs", description="MongoDB, PostgreSQL, REST, GraphQL", duration="2 months"),
            RoadmapStep(step=5, title="Deploy & Portfolio", description="Deploy projects on Vercel/AWS, build portfolio", duration="1-2 months"),
        ],
        keywords=["fullstack", "full stack", "web developer", "frontend", "backend", "mern", "react", "node"],
        related_careers=["Software Developer", "Frontend Developer", "Backend Developer"],
    ),
    # ─── 6 Cloud Architect ──────────────────────────────
    CareerPath(
        title="Cloud Architect",
        category=CareerCategory.CLOUD_AND_DEVOPS,
        description="Design and manage cloud infrastructure solutions. High-paying role requiring deep knowledge of cloud platforms and system design.",
        required_skills=["AWS/Azure/GCP", "System Design", "Networking", "Security", "Terraform", "Microservices", "Docker", "Kubernetes"],
        recommended_subjects=["Computer Networks", "Operating Systems", "Database Management Systems"],
        recommended_electives=["Cloud Computing Services"],
        min_cgpa_recommended=7.0,
        job_titles=["Cloud Architect", "Solutions Architect", "Cloud Infrastructure Engineer"],
        salary_range=SalaryRange(entry_level="6-12 LPA", mid_level="15-30 LPA", senior_level="30-60 LPA", top_companies="40-80+ LPA"),
        top_companies_india=["Amazon India", "Microsoft India", "Google Cloud India", "Infosys", "TCS"],
        top_companies_global=["Amazon", "Microsoft", "Google", "Salesforce", "Oracle"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — cloud adoption accelerating globally",
        certifications=["AWS Solutions Architect Professional", "Azure Solutions Architect Expert", "Google Cloud Professional Architect"],
        roadmap=[
            RoadmapStep(step=1, title="Cloud Fundamentals", description="Start with AWS Cloud Practitioner or Azure Fundamentals", duration="2 months"),
            RoadmapStep(step=2, title="Core Services", description="Compute, storage, networking, databases on your chosen platform", duration="3 months"),
            RoadmapStep(step=3, title="Architecture Patterns", description="Microservices, serverless, event-driven architectures", duration="3 months"),
            RoadmapStep(step=4, title="Security & Compliance", description="IAM, encryption, compliance frameworks", duration="2 months"),
            RoadmapStep(step=5, title="Professional Certification", description="AWS Solutions Architect Associate → Professional", duration="3-6 months"),
        ],
        keywords=["cloud", "architect", "aws", "azure", "gcp", "infrastructure", "solutions"],
        related_careers=["DevOps Engineer", "Software Developer"],
    ),
    # ─── 7 ML Engineer ─────────────────────────────────
    CareerPath(
        title="ML Engineer",
        category=CareerCategory.DATA_AND_AI,
        description="Build and deploy machine learning models at scale. Combines software engineering with data science for production ML systems.",
        required_skills=["Python", "TensorFlow/PyTorch", "MLOps", "Docker", "SQL", "Feature Engineering", "Model Deployment", "Cloud ML Services"],
        recommended_subjects=["Engineering Mathematics-III", "Engineering Mathematics-IV", "Python Programming", "Data Structures and Algorithms"],
        recommended_electives=["Machine Learning", "Deep Learning"],
        min_cgpa_recommended=7.0,
        job_titles=["ML Engineer", "Applied ML Engineer", "MLOps Engineer", "AI Engineer"],
        salary_range=SalaryRange(entry_level="8-15 LPA", mid_level="15-30 LPA", senior_level="30-50 LPA", top_companies="35-80+ LPA"),
        top_companies_india=["Google India", "Amazon India", "Flipkart", "Ola", "Jio", "Samsung R&D"],
        top_companies_global=["Google DeepMind", "OpenAI", "Meta AI", "Apple ML", "NVIDIA"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — AI/ML is transforming every industry",
        certifications=["Google ML Engineer", "AWS ML Specialty", "TensorFlow Developer"],
        roadmap=[
            RoadmapStep(step=1, title="Math & Statistics", description="Linear algebra, probability, optimization", duration="3 months"),
            RoadmapStep(step=2, title="ML Algorithms", description="Regression, classification, clustering, ensemble methods", duration="3 months"),
            RoadmapStep(step=3, title="Deep Learning", description="Neural networks, CNNs, RNNs, Transformers using PyTorch/TF", duration="3-4 months"),
            RoadmapStep(step=4, title="MLOps", description="Model serving, monitoring, CI/CD for ML, MLflow", duration="2-3 months"),
            RoadmapStep(step=5, title="Production Projects", description="End-to-end ML projects with deployment", duration="Ongoing"),
        ],
        keywords=["ml engineer", "machine learning engineer", "mlops", "deep learning", "ai engineer", "model deployment"],
        related_careers=["Data Scientist", "AI Research Engineer", "NLP Engineer"],
    ),
    # ─── 8 Data Analyst ────────────────────────────────
    CareerPath(
        title="Data Analyst",
        category=CareerCategory.DATA_AND_AI,
        description="Analyze data to provide business insights. Great entry point into the data field with lower barrier than Data Scientist roles.",
        required_skills=["SQL", "Excel", "Python/R", "Tableau/Power BI", "Statistics", "Data Cleaning", "Communication"],
        recommended_subjects=["Database Management Systems", "Engineering Mathematics-IV", "Python Programming"],
        recommended_electives=["Data Warehouse and Mining", "Big Data Analytics"],
        min_cgpa_recommended=6.0,
        job_titles=["Data Analyst", "Business Analyst", "BI Analyst", "Analytics Consultant"],
        salary_range=SalaryRange(entry_level="3-6 LPA", mid_level="7-14 LPA", senior_level="14-25 LPA", top_companies="15-35 LPA"),
        top_companies_india=["Mu Sigma", "Deloitte India", "EY", "KPMG", "Accenture", "Amazon"],
        top_companies_global=["McKinsey", "BCG", "Google", "Airbnb"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — every company needs data-driven decisions",
        certifications=["Google Data Analytics", "Microsoft Power BI", "Tableau Desktop Specialist"],
        roadmap=[
            RoadmapStep(step=1, title="SQL Mastery", description="Complex queries, joins, window functions, optimization", duration="2 months"),
            RoadmapStep(step=2, title="Excel & Visualization", description="Advanced Excel, Tableau or Power BI", duration="2 months"),
            RoadmapStep(step=3, title="Python for Analysis", description="Pandas, NumPy, Matplotlib for data manipulation", duration="2-3 months"),
            RoadmapStep(step=4, title="Statistics", description="Hypothesis testing, A/B testing, regression basics", duration="2 months"),
            RoadmapStep(step=5, title="Portfolio Projects", description="Real-world datasets, Kaggle notebooks, dashboards", duration="Ongoing"),
        ],
        keywords=["data analyst", "analytics", "business intelligence", "bi", "tableau", "power bi", "sql"],
        related_careers=["Data Scientist", "Business Analyst"],
    ),
    # ─── 9 Mobile App Developer ────────────────────────
    CareerPath(
        title="Mobile App Developer",
        category=CareerCategory.SOFTWARE_DEVELOPMENT,
        description="Build native and cross-platform mobile applications. Huge market in India with billions of smartphone users.",
        required_skills=["Flutter/React Native", "Dart/JavaScript", "REST APIs", "State Management", "UI/UX", "Firebase", "Git"],
        recommended_subjects=["Data Structures and Algorithms", "Database Management Systems", "Software Engineering"],
        recommended_electives=["Mobile Computing"],
        min_cgpa_recommended=6.0,
        job_titles=["Mobile Developer", "Flutter Developer", "Android Developer", "iOS Developer", "React Native Developer"],
        salary_range=SalaryRange(entry_level="4-8 LPA", mid_level="8-18 LPA", senior_level="18-30 LPA", top_companies="20-45+ LPA"),
        top_companies_india=["CRED", "PhonePe", "Swiggy", "Zomato", "Paytm", "Dream11"],
        top_companies_global=["Google", "Apple", "Meta", "Uber", "Airbnb"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — mobile-first India",
        certifications=["Google Associate Android Developer", "Flutter Certification"],
        roadmap=[
            RoadmapStep(step=1, title="Dart & Flutter Basics", description="Learn Dart language and Flutter framework", duration="2-3 months"),
            RoadmapStep(step=2, title="UI & State Management", description="Material Design, Provider/Riverpod/Bloc", duration="2 months"),
            RoadmapStep(step=3, title="APIs & Backend", description="REST API integration, Firebase, local storage", duration="2 months"),
            RoadmapStep(step=4, title="Publish Apps", description="Build and publish 2-3 apps on Play Store", duration="2-3 months"),
            RoadmapStep(step=5, title="Advanced Topics", description="Animations, platform channels, testing, CI/CD", duration="Ongoing"),
        ],
        keywords=["mobile", "app", "android", "ios", "flutter", "react native", "dart"],
        related_careers=["Full Stack Developer", "UI/UX Designer"],
    ),
    # ─── 10 Blockchain Developer ───────────────────────
    CareerPath(
        title="Blockchain Developer",
        category=CareerCategory.SOFTWARE_DEVELOPMENT,
        description="Build decentralized applications and smart contracts. Emerging field in India with growing fintech and Web3 adoption.",
        required_skills=["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Cryptography", "JavaScript", "Node.js", "DeFi concepts"],
        recommended_subjects=["Cryptography & Network Security", "Data Structures and Algorithms", "Computer Networks"],
        recommended_electives=["Blockchain Technology"],
        min_cgpa_recommended=7.0,
        job_titles=["Blockchain Developer", "Smart Contract Developer", "Web3 Developer", "DeFi Engineer"],
        salary_range=SalaryRange(entry_level="6-12 LPA", mid_level="15-30 LPA", senior_level="30-60 LPA", top_companies="35-80+ LPA"),
        top_companies_india=["Polygon (Matic)", "CoinDCX", "WazirX", "Zerodha (Crypto)", "Binance India"],
        top_companies_global=["Consensys", "Chainlink", "Alchemy", "Coinbase", "Binance"],
        market_demand=DemandLevel.EMERGING,
        growth_potential="High — Web3 and DeFi are growing rapidly",
        certifications=["Certified Blockchain Developer", "Ethereum Developer Certification"],
        roadmap=[
            RoadmapStep(step=1, title="Blockchain Fundamentals", description="Understand distributed ledger, consensus, hashing", duration="1-2 months"),
            RoadmapStep(step=2, title="Solidity & Smart Contracts", description="Write and deploy smart contracts on Ethereum", duration="3 months"),
            RoadmapStep(step=3, title="DApp Development", description="Build frontend with Web3.js/ethers.js", duration="2-3 months"),
            RoadmapStep(step=4, title="DeFi & Advanced", description="Token standards, DeFi protocols, Layer-2 solutions", duration="3 months"),
            RoadmapStep(step=5, title="Hackathons & Contribute", description="Participate in ETH hackathons, contribute to open-source", duration="Ongoing"),
        ],
        keywords=["blockchain", "web3", "smart contract", "ethereum", "solidity", "defi", "crypto", "decentralized"],
        related_careers=["Software Developer", "Cybersecurity Analyst"],
    ),
    # ─── 11 IoT Developer ──────────────────────────────
    CareerPath(
        title="IoT Developer",
        category=CareerCategory.NETWORKING_AND_IOT,
        description="Build connected device ecosystems combining hardware and software. Growing rapidly with India's smart city and Industry 4.0 initiatives.",
        required_skills=["Embedded C", "Python", "MQTT", "Raspberry Pi", "Arduino", "Cloud IoT", "Sensors", "Edge Computing"],
        recommended_subjects=["Microcontroller & Embedded Systems", "Computer Networks", "Digital Logic & Design"],
        recommended_electives=["Internet of Things", "Edge Computing"],
        min_cgpa_recommended=6.0,
        job_titles=["IoT Developer", "Embedded Systems Engineer", "IoT Solutions Architect"],
        salary_range=SalaryRange(entry_level="4-7 LPA", mid_level="8-16 LPA", senior_level="16-30 LPA", top_companies="20-40 LPA"),
        top_companies_india=["Bosch India", "Samsung R&D", "Tata Elxsi", "L&T Technology", "Honeywell India"],
        top_companies_global=["Siemens", "Bosch", "Cisco", "Intel", "AWS IoT"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — Smart cities, Industry 4.0, connected vehicles",
        certifications=["AWS IoT Core", "Cisco IoT Fundamentals"],
        roadmap=[
            RoadmapStep(step=1, title="Microcontroller Basics", description="Arduino, ESP32, basic sensor interfacing", duration="2 months"),
            RoadmapStep(step=2, title="Communication Protocols", description="MQTT, HTTP, BLE, LoRa, WiFi", duration="2 months"),
            RoadmapStep(step=3, title="Cloud Integration", description="AWS IoT, Azure IoT Hub, data pipelines", duration="2-3 months"),
            RoadmapStep(step=4, title="Edge Computing", description="TensorFlow Lite, edge ML, real-time processing", duration="2-3 months"),
            RoadmapStep(step=5, title="Projects", description="Build smart home or environmental monitoring system", duration="Ongoing"),
        ],
        keywords=["iot", "internet of things", "embedded", "sensors", "raspberry pi", "arduino", "edge computing"],
        related_careers=["Embedded Systems Engineer", "Cloud Architect"],
    ),
    # ─── 12 Product Manager (Tech) ─────────────────────
    CareerPath(
        title="Product Manager (Tech)",
        category=CareerCategory.MANAGEMENT,
        description="Drive product strategy and execution. Bridges business, design, and engineering. Popular career pivot for engineers at top Indian startups.",
        required_skills=["Product Thinking", "Data Analysis", "SQL", "Wireframing", "A/B Testing", "Agile/Scrum", "Communication", "User Research"],
        recommended_subjects=["Software Engineering", "Database Management Systems", "Data Structures and Algorithms"],
        recommended_electives=["Project Management", "Business Analytics", "Entrepreneurship Development"],
        min_cgpa_recommended=7.0,
        job_titles=["Associate Product Manager", "Product Manager", "Senior PM", "Group PM", "VP Product"],
        salary_range=SalaryRange(entry_level="8-15 LPA", mid_level="18-35 LPA", senior_level="35-60 LPA", top_companies="40-1Cr+ LPA"),
        top_companies_india=["Flipkart", "Swiggy", "CRED", "Razorpay", "PhonePe", "Meesho", "Dream11"],
        top_companies_global=["Google", "Meta", "Amazon", "Microsoft", "Stripe"],
        market_demand=DemandLevel.HIGH,
        growth_potential="Very High — every tech company needs strong PMs",
        certifications=["Google PM Certificate", "Product School Certification", "Pragmatic Institute"],
        roadmap=[
            RoadmapStep(step=1, title="Build Technical Foundation", description="Strong coding + system design understanding", duration="During college"),
            RoadmapStep(step=2, title="Learn Product Frameworks", description="Study PRDs, user stories, RICE/ICE, jobs-to-be-done", duration="2-3 months"),
            RoadmapStep(step=3, title="Data & Analytics", description="SQL, metrics, A/B testing, funnel analysis", duration="2 months"),
            RoadmapStep(step=4, title="Build & Ship a Product", description="Create a side project, get real users, iterate", duration="3-4 months"),
            RoadmapStep(step=5, title="APM Programs", description="Apply to Google APM, Flipkart APM, Razorpay APM", duration="Final year"),
        ],
        keywords=["product manager", "pm", "product", "apm", "strategy", "management", "business"],
        related_careers=["Business Analyst", "Software Developer", "Data Analyst"],
    ),
    # ─── 13 AI Research Engineer ────────────────────────
    CareerPath(
        title="AI Research Engineer",
        category=CareerCategory.DATA_AND_AI,
        description="Push the boundaries of artificial intelligence through novel research and implementation. Requires strong mathematical foundations and research aptitude.",
        required_skills=["Python", "PyTorch/TensorFlow", "Linear Algebra", "Probability", "NLP/CV", "Research Paper Reading", "Experiment Design", "LaTeX"],
        recommended_subjects=["Engineering Mathematics-III", "Engineering Mathematics-IV", "Artificial Intelligence", "Design & Analysis of Algorithms"],
        recommended_electives=["Deep Learning", "Natural Language Processing", "Quantum Computing"],
        min_cgpa_recommended=8.0,
        job_titles=["AI Research Engineer", "Research Scientist", "Applied Researcher", "ML Research Intern"],
        salary_range=SalaryRange(entry_level="10-18 LPA", mid_level="20-40 LPA", senior_level="40-80 LPA", top_companies="50-1.5Cr+ LPA"),
        top_companies_india=["Google Research India", "Microsoft Research India", "Samsung R&D", "IBM Research", "TCS Research"],
        top_companies_global=["Google DeepMind", "OpenAI", "Meta FAIR", "Anthropic", "NVIDIA Research"],
        market_demand=DemandLevel.HIGH,
        growth_potential="Very High — AI research defines the future of technology",
        certifications=["Deep Learning Specialization (Coursera)", "Stanford CS229/CS231n (audit)"],
        roadmap=[
            RoadmapStep(step=1, title="Mathematics Deep Dive", description="Linear algebra, probability, optimization, information theory", duration="4-6 months"),
            RoadmapStep(step=2, title="ML/DL Mastery", description="Implement papers from scratch, understand architectures", duration="6 months"),
            RoadmapStep(step=3, title="Research Skills", description="Read 50+ papers, reproduce results, identify gaps", duration="6 months"),
            RoadmapStep(step=4, title="Publish", description="Work on novel ideas, submit to conferences (NeurIPS, ICML, AAAI)", duration="6-12 months"),
            RoadmapStep(step=5, title="MS/PhD or Research Lab", description="Consider MS/PhD at top universities or join research labs", duration="2-5 years"),
        ],
        keywords=["ai research", "research scientist", "deep learning research", "nlp research", "computer vision research", "phd"],
        related_careers=["Data Scientist", "ML Engineer", "NLP Engineer"],
    ),
    # ─── 14 Network Engineer ────────────────────────────
    CareerPath(
        title="Network Engineer",
        category=CareerCategory.NETWORKING_AND_IOT,
        description="Design, implement, and manage computer networks. Foundational IT role with strong demand in India's growing enterprise and telecom sectors.",
        required_skills=["TCP/IP", "Routing & Switching", "Cisco IOS", "Firewalls", "VPN", "DNS/DHCP", "Linux", "Network Monitoring"],
        recommended_subjects=["Computer Networks", "Operating Systems", "Cryptography & Network Security"],
        recommended_electives=["Wireless Technology", "Cloud Computing Services"],
        min_cgpa_recommended=6.0,
        job_titles=["Network Engineer", "Network Administrator", "NOC Engineer", "Network Architect"],
        salary_range=SalaryRange(entry_level="3-6 LPA", mid_level="7-15 LPA", senior_level="15-30 LPA", top_companies="18-40 LPA"),
        top_companies_india=["Cisco India", "Jio", "Airtel", "TCS", "Wipro", "HCL", "Juniper India"],
        top_companies_global=["Cisco", "Juniper Networks", "Arista", "Palo Alto Networks"],
        market_demand=DemandLevel.HIGH,
        growth_potential="Stable — evolving towards SDN and cloud networking",
        certifications=["CCNA", "CCNP", "CompTIA Network+", "Juniper JNCIA"],
        roadmap=[
            RoadmapStep(step=1, title="Networking Basics", description="OSI model, TCP/IP, subnetting, VLANs", duration="2-3 months"),
            RoadmapStep(step=2, title="Cisco / Juniper", description="Router/switch configuration, OSPF, BGP", duration="3 months"),
            RoadmapStep(step=3, title="Security Basics", description="Firewalls, ACLs, VPN, IDS/IPS", duration="2 months"),
            RoadmapStep(step=4, title="CCNA Certification", description="Study and pass Cisco CCNA 200-301", duration="3-4 months"),
            RoadmapStep(step=5, title="Cloud Networking", description="AWS VPC, Azure Networking, SDN concepts", duration="2-3 months"),
        ],
        keywords=["network", "networking", "cisco", "ccna", "router", "switch", "telecom", "infrastructure"],
        related_careers=["Cybersecurity Analyst", "Cloud Architect", "DevOps Engineer"],
    ),
    # ─── 15 UI/UX Designer ─────────────────────────────
    CareerPath(
        title="UI/UX Designer",
        category=CareerCategory.DESIGN,
        description="Design user interfaces and experiences for digital products. Growing role in India as companies focus on user-centric design.",
        required_skills=["Figma", "Adobe XD", "User Research", "Wireframing", "Prototyping", "Design Systems", "HTML/CSS", "Usability Testing"],
        recommended_subjects=["Software Engineering", "Database Management Systems"],
        recommended_electives=["AR/VR Technologies", "Digital Marketing"],
        min_cgpa_recommended=6.0,
        job_titles=["UI Designer", "UX Designer", "Product Designer", "Interaction Designer", "UX Researcher"],
        salary_range=SalaryRange(entry_level="3-7 LPA", mid_level="8-18 LPA", senior_level="18-35 LPA", top_companies="20-50+ LPA"),
        top_companies_india=["CRED", "Swiggy", "Flipkart", "Razorpay", "Freshworks", "Zomato"],
        top_companies_global=["Apple", "Google", "Airbnb", "Figma", "Spotify"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — design-led companies outperform competitors",
        certifications=["Google UX Design Certificate", "Interaction Design Foundation"],
        roadmap=[
            RoadmapStep(step=1, title="Design Fundamentals", description="Typography, color theory, layout, visual hierarchy", duration="2 months"),
            RoadmapStep(step=2, title="Tool Mastery", description="Figma (primary), Adobe XD, prototyping tools", duration="2 months"),
            RoadmapStep(step=3, title="UX Research", description="User interviews, personas, journey maps, usability testing", duration="2-3 months"),
            RoadmapStep(step=4, title="Design Systems", description="Component libraries, style guides, accessibility", duration="2 months"),
            RoadmapStep(step=5, title="Portfolio", description="Build 4-5 case studies showing process and outcomes", duration="Ongoing"),
        ],
        keywords=["ui", "ux", "design", "user interface", "user experience", "figma", "product design", "designer"],
        related_careers=["Full Stack Developer", "Product Manager"],
    ),
    # ─── 16 QA / Test Automation Engineer ───────────────
    CareerPath(
        title="QA / Test Automation Engineer",
        category=CareerCategory.SOFTWARE_DEVELOPMENT,
        description="Ensure software quality through automated and manual testing. Strong demand in India's IT services and product companies.",
        required_skills=["Selenium", "Python/Java", "API Testing", "CI/CD", "JIRA", "SQL", "Performance Testing", "Test Frameworks"],
        recommended_subjects=["Software Engineering", "Data Structures and Algorithms", "Database Management Systems"],
        recommended_electives=["Software Testing", "DevOps Laboratory"],
        min_cgpa_recommended=6.0,
        job_titles=["QA Engineer", "SDET", "Test Automation Engineer", "Quality Analyst"],
        salary_range=SalaryRange(entry_level="3-6 LPA", mid_level="7-15 LPA", senior_level="15-28 LPA", top_companies="18-40 LPA"),
        top_companies_india=["TCS", "Infosys", "Cognizant", "Accenture", "Flipkart", "Freshworks"],
        top_companies_global=["Google", "Microsoft", "Amazon", "Apple"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — shift-left testing and SDET roles growing",
        certifications=["ISTQB Foundation", "Selenium Certification", "AWS Certified Cloud Practitioner"],
        roadmap=[
            RoadmapStep(step=1, title="Testing Fundamentals", description="Test types, STLC, bug lifecycle, test cases", duration="1-2 months"),
            RoadmapStep(step=2, title="Programming", description="Python or Java for test automation", duration="2-3 months"),
            RoadmapStep(step=3, title="Selenium & Frameworks", description="Selenium WebDriver, TestNG/PyTest, Page Object Model", duration="2-3 months"),
            RoadmapStep(step=4, title="API & Performance Testing", description="Postman, REST Assured, JMeter, k6", duration="2 months"),
            RoadmapStep(step=5, title="CI/CD Integration", description="Jenkins/GitHub Actions, Docker, test pipelines", duration="2 months"),
        ],
        keywords=["qa", "testing", "automation", "sdet", "quality", "selenium", "test engineer"],
        related_careers=["Software Developer", "DevOps Engineer"],
    ),
    # ─── 17 NLP Engineer ───────────────────────────────
    CareerPath(
        title="NLP Engineer",
        category=CareerCategory.DATA_AND_AI,
        description="Build systems that understand and generate human language. Booming field with ChatGPT, voice assistants, and multilingual India.",
        required_skills=["Python", "NLP Libraries (spaCy, NLTK, HuggingFace)", "Transformers", "Deep Learning", "Text Processing", "LLMs", "Prompt Engineering"],
        recommended_subjects=["Artificial Intelligence", "Engineering Mathematics-III", "Python Programming"],
        recommended_electives=["Natural Language Processing", "Deep Learning"],
        min_cgpa_recommended=7.5,
        job_titles=["NLP Engineer", "Conversational AI Developer", "LLM Engineer", "Language AI Researcher"],
        salary_range=SalaryRange(entry_level="8-14 LPA", mid_level="15-30 LPA", senior_level="30-55 LPA", top_companies="40-80+ LPA"),
        top_companies_india=["Google India", "Microsoft India", "Flipkart", "Haptik", "Yellow.ai", "Krutrim"],
        top_companies_global=["OpenAI", "Google", "Meta", "Anthropic", "Cohere"],
        market_demand=DemandLevel.VERY_HIGH,
        growth_potential="Very High — LLMs and GenAI are the biggest tech trend",
        certifications=["HuggingFace NLP Course (free)", "DeepLearning.AI NLP Specialization"],
        roadmap=[
            RoadmapStep(step=1, title="NLP Basics", description="Tokenization, stemming, POS tagging, Named Entity Recognition", duration="2 months"),
            RoadmapStep(step=2, title="Classical NLP", description="TF-IDF, Word2Vec, sentiment analysis, text classification", duration="2-3 months"),
            RoadmapStep(step=3, title="Transformers", description="Attention mechanism, BERT, GPT, T5 architectures", duration="3 months"),
            RoadmapStep(step=4, title="LLM Applications", description="Fine-tuning, RAG, prompt engineering, LangChain", duration="3 months"),
            RoadmapStep(step=5, title="Build & Deploy", description="Build chatbots, Q&A systems, deploy with APIs", duration="Ongoing"),
        ],
        keywords=["nlp", "natural language processing", "chatbot", "llm", "gpt", "transformers", "language model", "conversational ai"],
        related_careers=["ML Engineer", "AI Research Engineer", "Data Scientist"],
    ),
    # ─── 18 Business Analyst ───────────────────────────
    CareerPath(
        title="Business Analyst",
        category=CareerCategory.MANAGEMENT,
        description="Analyze business processes and recommend improvements using data and technology. Strong bridge role between business and IT teams.",
        required_skills=["Requirements Analysis", "SQL", "Excel", "JIRA", "Process Mapping", "UML Diagrams", "Communication", "Agile"],
        recommended_subjects=["Software Engineering", "Database Management Systems"],
        recommended_electives=["Project Management", "Business Analytics", "Entrepreneurship Development"],
        min_cgpa_recommended=6.5,
        job_titles=["Business Analyst", "Systems Analyst", "IT Business Analyst", "Functional Consultant"],
        salary_range=SalaryRange(entry_level="4-7 LPA", mid_level="8-16 LPA", senior_level="16-30 LPA", top_companies="18-40 LPA"),
        top_companies_india=["Deloitte", "EY", "KPMG", "Accenture", "Capgemini", "TCS"],
        top_companies_global=["McKinsey", "BCG", "Bain", "Accenture"],
        market_demand=DemandLevel.HIGH,
        growth_potential="High — digital transformation needs analysts",
        certifications=["CBAP", "PMI-PBA", "Six Sigma Green Belt"],
        roadmap=[
            RoadmapStep(step=1, title="BA Fundamentals", description="Requirements elicitation, BRD/SRS, stakeholder management", duration="2 months"),
            RoadmapStep(step=2, title="Data & SQL", description="SQL for analysis, Excel advanced features, Power BI", duration="2-3 months"),
            RoadmapStep(step=3, title="Process Modeling", description="BPMN, UML, use cases, user stories", duration="2 months"),
            RoadmapStep(step=4, title="Agile & Tools", description="Scrum, Kanban, JIRA, Confluence", duration="1-2 months"),
            RoadmapStep(step=5, title="Domain Knowledge", description="Pick a domain (fintech, healthcare, e-commerce)", duration="Ongoing"),
        ],
        keywords=["business analyst", "ba", "requirements", "process", "consulting", "systems analyst"],
        related_careers=["Product Manager", "Data Analyst", "Project Manager"],
    ),
]


async def seed_careers():
    """Seed career paths into MongoDB"""
    from app.models.career import CareerPath as CP

    existing = await CP.find().count()
    if existing > 0:
        logger.info(f"Career data already exists ({existing} records). Deleting and re-seeding...")
        await CP.find().delete()

    await CP.insert_many(CAREERS)
    logger.info(f"✅ Seeded {len(CAREERS)} career paths")
    return len(CAREERS)


# CLI entry point
if __name__ == "__main__":
    from motor.motor_asyncio import AsyncIOMotorClient
    from beanie import init_beanie
    from app.core.config import settings
    from app.models.career import CareerPath as CP

    async def main():
        client = AsyncIOMotorClient(settings.MONGODB_URL)
        await init_beanie(database=client[settings.MONGODB_DATABASE], document_models=[CP])
        count = await seed_careers()
        print(f"Done! Seeded {count} careers.")
        client.close()

    asyncio.run(main())