# academic-advisor-backend/scripts/seed_career_data.py
import asyncio
import logging

logger = logging.getLogger(__name__)

# Define as dictionaries - use UPPERCASE enum names (will convert later)
CAREERS_DATA = [
    # ─── 1 Software Developer ───────────────────────────
    {
        "title": "Software Developer",
        "category": "SOFTWARE_DEVELOPMENT",  # Use enum NAME (uppercase)
        "description": "Design, develop, and maintain software applications. Full lifecycle involvement from requirements to deployment. One of the most in-demand roles in the Indian IT industry.",
        "required_skills": ["Python", "Java", "JavaScript", "Data Structures", "Algorithms", "Git", "SQL", "REST APIs", "System Design"],
        "recommended_subjects": ["Data Structures and Algorithms", "Software Engineering", "Database Management Systems", "Operating Systems"],
        "recommended_electives": ["Cloud Computing Services", "Software Testing"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Software Engineer", "SDE-1", "SDE-2", "Application Developer", "Backend Developer"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "10-20 LPA", "senior_level": "20-40 LPA", "top_companies": "25-60+ LPA"},
        "top_companies_india": ["TCS", "Infosys", "Wipro", "HCL", "Cognizant", "Flipkart", "Razorpay", "PhonePe", "Juspay"],
        "top_companies_global": ["Google", "Microsoft", "Amazon", "Meta", "Apple"],
        "market_demand": "VERY_HIGH",  # Use enum NAME (uppercase)
        "growth_potential": "Very High — constant demand across all industries",
        "certifications": ["AWS Certified Developer", "Oracle Java Certification", "Microsoft Azure Developer"],
        "roadmap": [
            {"step": 1, "title": "Master DSA & OOP", "description": "Solve 200+ problems on LeetCode/GFG", "duration": "3-4 months"},
            {"step": 2, "title": "Learn a Framework", "description": "Spring Boot (Java) or Django/FastAPI (Python) or Node.js", "duration": "2-3 months"},
            {"step": 3, "title": "Build Projects", "description": "Build 2-3 full-stack projects with real-world features", "duration": "3-4 months"},
            {"step": 4, "title": "System Design Basics", "description": "Study scalability, load balancing, caching, databases", "duration": "2 months"},
            {"step": 5, "title": "Apply & Interview", "description": "Target product companies via campus/off-campus drives", "duration": "Ongoing"},
        ],
        "keywords": ["software", "developer", "engineer", "coding", "programming", "sde", "backend", "fullstack"],
        "related_careers": ["Full Stack Developer", "DevOps Engineer", "Cloud Architect"],
    },
    # ─── 2 Data Scientist ───────────────────────────────
    {
        "title": "Data Scientist",
        "category": "DATA_AND_AI",
        "description": "Extract insights from complex data using statistics, machine learning, and domain expertise. High-paying role with growing demand in India's analytics industry.",
        "required_skills": ["Python", "Statistics", "Machine Learning", "SQL", "Pandas", "NumPy", "Scikit-learn", "Data Visualization", "Deep Learning"],
        "recommended_subjects": ["Engineering Mathematics-III", "Engineering Mathematics-IV", "Python Programming", "Database Management Systems"],
        "recommended_electives": ["Machine Learning", "Big Data Analytics", "Data Warehouse and Mining"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Data Scientist", "ML Engineer", "Data Analyst", "Research Scientist", "Applied Scientist"],
        "salary_range": {"entry_level": "6-12 LPA", "mid_level": "12-25 LPA", "senior_level": "25-50 LPA", "top_companies": "30-70+ LPA"},
        "top_companies_india": ["Flipkart", "Amazon India", "Mu Sigma", "Fractal Analytics", "Tiger Analytics", "Paytm", "PhonePe"],
        "top_companies_global": ["Google", "Meta", "Netflix", "Apple", "OpenAI"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — data-driven decision making is transforming every industry",
        "certifications": ["Google Data Analytics Certificate", "IBM Data Science Professional", "AWS ML Specialty"],
        "roadmap": [
            {"step": 1, "title": "Statistics & Math", "description": "Master probability, linear algebra, calculus", "duration": "2-3 months"},
            {"step": 2, "title": "Python for Data Science", "description": "Learn Pandas, NumPy, Matplotlib, Seaborn", "duration": "2 months"},
            {"step": 3, "title": "Machine Learning", "description": "Study supervised/unsupervised algorithms, model evaluation", "duration": "3-4 months"},
            {"step": 4, "title": "Deep Learning & NLP", "description": "Neural networks, CNNs, RNNs, Transformers", "duration": "3 months"},
            {"step": 5, "title": "Kaggle & Portfolio", "description": "Compete on Kaggle, build end-to-end projects", "duration": "Ongoing"},
        ],
        "keywords": ["data", "scientist", "analytics", "ml", "machine learning", "ai", "statistics", "analysis"],
        "related_careers": ["ML Engineer", "Data Analyst", "AI Research Engineer"],
    },
    # ─── 3 DevOps Engineer ──────────────────────────────
    {
        "title": "DevOps Engineer",
        "category": "CLOUD_AND_DEVOPS",
        "description": "Bridge development and operations through CI/CD pipelines, infrastructure automation, and container orchestration. Critical role in modern software delivery.",
        "required_skills": ["Linux", "Docker", "Kubernetes", "CI/CD", "AWS/Azure", "Terraform", "Git", "Python/Bash Scripting", "Monitoring"],
        "recommended_subjects": ["Operating Systems", "Computer Networks", "Software Engineering"],
        "recommended_electives": ["Cloud Computing Services"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["DevOps Engineer", "SRE", "Platform Engineer", "Cloud Engineer", "Release Engineer"],
        "salary_range": {"entry_level": "5-10 LPA", "mid_level": "12-22 LPA", "senior_level": "22-40 LPA", "top_companies": "25-55+ LPA"},
        "top_companies_india": ["Flipkart", "Razorpay", "Dream11", "Zerodha", "Freshworks", "Zomato"],
        "top_companies_global": ["Google", "Amazon", "Netflix", "Spotify", "HashiCorp"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — every company needs DevOps as they scale",
        "certifications": ["AWS Solutions Architect", "Kubernetes CKA/CKAD", "Docker Certified Associate", "Terraform Associate"],
        "roadmap": [
            {"step": 1, "title": "Linux & Networking", "description": "Master Linux commands, networking, SSH, firewalls", "duration": "2 months"},
            {"step": 2, "title": "Containers & Orchestration", "description": "Docker, Docker Compose, Kubernetes basics", "duration": "2-3 months"},
            {"step": 3, "title": "CI/CD Pipelines", "description": "Jenkins, GitHub Actions, GitLab CI", "duration": "2 months"},
            {"step": 4, "title": "Cloud Platforms", "description": "AWS or Azure — compute, networking, storage, IAM", "duration": "3 months"},
            {"step": 5, "title": "IaC & Monitoring", "description": "Terraform, Ansible, Prometheus, Grafana", "duration": "2 months"},
        ],
        "keywords": ["devops", "cicd", "docker", "kubernetes", "cloud", "infrastructure", "deployment", "automation", "sre"],
        "related_careers": ["Cloud Architect", "Software Developer", "SRE"],
    },
    # ─── 4 Cybersecurity Analyst ────────────────────────
    {
        "title": "Cybersecurity Analyst",
        "category": "SECURITY",
        "description": "Protect systems and networks from cyber threats. Growing rapidly in India due to digital transformation and regulatory requirements.",
        "required_skills": ["Network Security", "Ethical Hacking", "SIEM Tools", "Cryptography", "Linux", "Wireshark", "Penetration Testing", "Firewalls"],
        "recommended_subjects": ["Computer Networks", "Operating Systems", "Cryptography & Network Security"],
        "recommended_electives": ["Ethical Hacking", "Cyber Security"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Security Analyst", "Penetration Tester", "SOC Analyst", "Security Engineer", "Threat Analyst"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "10-20 LPA", "senior_level": "20-35 LPA", "top_companies": "25-50+ LPA"},
        "top_companies_india": ["Tata CISO", "Paladion", "Quick Heal", "Lucideus", "CrowdStrike India", "Palo Alto India"],
        "top_companies_global": ["CrowdStrike", "Palo Alto Networks", "Fortinet", "FireEye", "Deloitte Cyber"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — cybersecurity talent gap is massive globally",
        "certifications": ["CompTIA Security+", "CEH (Certified Ethical Hacker)", "CISSP", "OSCP"],
        "roadmap": [
            {"step": 1, "title": "Networking Fundamentals", "description": "TCP/IP, DNS, HTTP, firewalls, VPNs", "duration": "2 months"},
            {"step": 2, "title": "Linux & Scripting", "description": "Linux admin, Bash/Python scripting", "duration": "2 months"},
            {"step": 3, "title": "Security Tools", "description": "Wireshark, Nmap, Metasploit, Burp Suite", "duration": "3 months"},
            {"step": 4, "title": "Certifications", "description": "Start with CompTIA Security+, then CEH", "duration": "3-6 months"},
            {"step": 5, "title": "CTFs & Labs", "description": "Practice on HackTheBox, TryHackMe", "duration": "Ongoing"},
        ],
        "keywords": ["cybersecurity", "security", "hacking", "ethical hacking", "penetration", "infosec", "soc"],
        "related_careers": ["Network Engineer", "Cloud Security Engineer"],
    },
    # ─── 5 Full Stack Developer ─────────────────────────
    {
        "title": "Full Stack Developer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Build complete web applications — frontend and backend. One of the most versatile and in-demand roles in the Indian startup ecosystem.",
        "required_skills": ["HTML/CSS", "JavaScript", "React/Angular/Vue", "Node.js/Python", "SQL/NoSQL", "REST APIs", "Git", "Docker"],
        "recommended_subjects": ["Database Management Systems", "Computer Networks", "Software Engineering", "Data Structures and Algorithms"],
        "recommended_electives": ["Cloud Computing Services", "Software Testing"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Full Stack Developer", "Web Developer", "MERN Stack Developer", "Software Engineer"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "10-18 LPA", "senior_level": "18-35 LPA", "top_companies": "20-50+ LPA"},
        "top_companies_india": ["Flipkart", "Swiggy", "CRED", "Razorpay", "Freshworks", "Zerodha", "Meesho"],
        "top_companies_global": ["Google", "Meta", "Shopify", "Stripe", "Vercel"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — every business needs web presence",
        "certifications": ["Meta Front-End Developer", "AWS Cloud Practitioner"],
        "roadmap": [
            {"step": 1, "title": "Frontend Basics", "description": "HTML, CSS, JavaScript, responsive design", "duration": "2-3 months"},
            {"step": 2, "title": "Frontend Framework", "description": "React.js or Angular — build SPAs", "duration": "2-3 months"},
            {"step": 3, "title": "Backend Development", "description": "Node.js + Express or Python + FastAPI", "duration": "2-3 months"},
            {"step": 4, "title": "Database & APIs", "description": "MongoDB, PostgreSQL, REST, GraphQL", "duration": "2 months"},
            {"step": 5, "title": "Deploy & Portfolio", "description": "Deploy projects on Vercel/AWS, build portfolio", "duration": "1-2 months"},
        ],
        "keywords": ["fullstack", "full stack", "web developer", "frontend", "backend", "mern", "react", "node"],
        "related_careers": ["Software Developer", "Frontend Developer", "Backend Developer"],
    },
    # ─── 6 Cloud Architect ──────────────────────────────
    {
        "title": "Cloud Architect",
        "category": "CLOUD_AND_DEVOPS",
        "description": "Design and manage cloud infrastructure solutions. High-paying role requiring deep knowledge of cloud platforms and system design.",
        "required_skills": ["AWS/Azure/GCP", "System Design", "Networking", "Security", "Terraform", "Microservices", "Docker", "Kubernetes"],
        "recommended_subjects": ["Computer Networks", "Operating Systems", "Database Management Systems"],
        "recommended_electives": ["Cloud Computing Services"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Cloud Architect", "Solutions Architect", "Cloud Infrastructure Engineer"],
        "salary_range": {"entry_level": "6-12 LPA", "mid_level": "15-30 LPA", "senior_level": "30-60 LPA", "top_companies": "40-80+ LPA"},
        "top_companies_india": ["Amazon India", "Microsoft India", "Google Cloud India", "Infosys", "TCS"],
        "top_companies_global": ["Amazon", "Microsoft", "Google", "Salesforce", "Oracle"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — cloud adoption accelerating globally",
        "certifications": ["AWS Solutions Architect Professional", "Azure Solutions Architect Expert", "Google Cloud Professional Architect"],
        "roadmap": [
            {"step": 1, "title": "Cloud Fundamentals", "description": "Start with AWS Cloud Practitioner or Azure Fundamentals", "duration": "2 months"},
            {"step": 2, "title": "Core Services", "description": "Compute, storage, networking, databases on your chosen platform", "duration": "3 months"},
            {"step": 3, "title": "Architecture Patterns", "description": "Microservices, serverless, event-driven architectures", "duration": "3 months"},
            {"step": 4, "title": "Security & Compliance", "description": "IAM, encryption, compliance frameworks", "duration": "2 months"},
            {"step": 5, "title": "Professional Certification", "description": "AWS Solutions Architect Associate → Professional", "duration": "3-6 months"},
        ],
        "keywords": ["cloud", "architect", "aws", "azure", "gcp", "infrastructure", "solutions"],
        "related_careers": ["DevOps Engineer", "Software Developer"],
    },
    # ─── 7 ML Engineer ─────────────────────────────────
    {
        "title": "ML Engineer",
        "category": "DATA_AND_AI",
        "description": "Build and deploy machine learning models at scale. Combines software engineering with data science for production ML systems.",
        "required_skills": ["Python", "TensorFlow/PyTorch", "MLOps", "Docker", "SQL", "Feature Engineering", "Model Deployment", "Cloud ML Services"],
        "recommended_subjects": ["Engineering Mathematics-III", "Engineering Mathematics-IV", "Python Programming", "Data Structures and Algorithms"],
        "recommended_electives": ["Machine Learning", "Deep Learning"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["ML Engineer", "Applied ML Engineer", "MLOps Engineer", "AI Engineer"],
        "salary_range": {"entry_level": "8-15 LPA", "mid_level": "15-30 LPA", "senior_level": "30-50 LPA", "top_companies": "35-80+ LPA"},
        "top_companies_india": ["Google India", "Amazon India", "Flipkart", "Ola", "Jio", "Samsung R&D"],
        "top_companies_global": ["Google DeepMind", "OpenAI", "Meta AI", "Apple ML", "NVIDIA"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — AI/ML is transforming every industry",
        "certifications": ["Google ML Engineer", "AWS ML Specialty", "TensorFlow Developer"],
        "roadmap": [
            {"step": 1, "title": "Math & Statistics", "description": "Linear algebra, probability, optimization", "duration": "3 months"},
            {"step": 2, "title": "ML Algorithms", "description": "Regression, classification, clustering, ensemble methods", "duration": "3 months"},
            {"step": 3, "title": "Deep Learning", "description": "Neural networks, CNNs, RNNs, Transformers using PyTorch/TF", "duration": "3-4 months"},
            {"step": 4, "title": "MLOps", "description": "Model serving, monitoring, CI/CD for ML, MLflow", "duration": "2-3 months"},
            {"step": 5, "title": "Production Projects", "description": "End-to-end ML projects with deployment", "duration": "Ongoing"},
        ],
        "keywords": ["ml engineer", "machine learning engineer", "mlops", "deep learning", "ai engineer", "model deployment"],
        "related_careers": ["Data Scientist", "AI Research Engineer", "NLP Engineer"],
    },
    # ─── 8 Data Analyst ────────────────────────────────
    {
        "title": "Data Analyst",
        "category": "DATA_AND_AI",
        "description": "Analyze data to provide business insights. Great entry point into the data field with lower barrier than Data Scientist roles.",
        "required_skills": ["SQL", "Excel", "Python/R", "Tableau/Power BI", "Statistics", "Data Cleaning", "Communication"],
        "recommended_subjects": ["Database Management Systems", "Engineering Mathematics-IV", "Python Programming"],
        "recommended_electives": ["Data Warehouse and Mining", "Big Data Analytics"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Data Analyst", "Business Analyst", "BI Analyst", "Analytics Consultant"],
        "salary_range": {"entry_level": "3-6 LPA", "mid_level": "7-14 LPA", "senior_level": "14-25 LPA", "top_companies": "15-35 LPA"},
        "top_companies_india": ["Mu Sigma", "Deloitte India", "EY", "KPMG", "Accenture", "Amazon"],
        "top_companies_global": ["McKinsey", "BCG", "Google", "Airbnb"],
        "market_demand": "HIGH",
        "growth_potential": "High — every company needs data-driven decisions",
        "certifications": ["Google Data Analytics", "Microsoft Power BI", "Tableau Desktop Specialist"],
        "roadmap": [
            {"step": 1, "title": "SQL Mastery", "description": "Complex queries, joins, window functions, optimization", "duration": "2 months"},
            {"step": 2, "title": "Excel & Visualization", "description": "Advanced Excel, Tableau or Power BI", "duration": "2 months"},
            {"step": 3, "title": "Python for Analysis", "description": "Pandas, NumPy, Matplotlib for data manipulation", "duration": "2-3 months"},
            {"step": 4, "title": "Statistics", "description": "Hypothesis testing, A/B testing, regression basics", "duration": "2 months"},
            {"step": 5, "title": "Portfolio Projects", "description": "Real-world datasets, Kaggle notebooks, dashboards", "duration": "Ongoing"},
        ],
        "keywords": ["data analyst", "analytics", "business intelligence", "bi", "tableau", "power bi", "sql"],
        "related_careers": ["Data Scientist", "Business Analyst"],
    },
    # ─── 9 Mobile App Developer ────────────────────────
    {
        "title": "Mobile App Developer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Build native and cross-platform mobile applications. Huge market in India with billions of smartphone users.",
        "required_skills": ["Flutter/React Native", "Dart/JavaScript", "REST APIs", "State Management", "UI/UX", "Firebase", "Git"],
        "recommended_subjects": ["Data Structures and Algorithms", "Database Management Systems", "Software Engineering"],
        "recommended_electives": ["Mobile Computing"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Mobile Developer", "Flutter Developer", "Android Developer", "iOS Developer", "React Native Developer"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "8-18 LPA", "senior_level": "18-30 LPA", "top_companies": "20-45+ LPA"},
        "top_companies_india": ["CRED", "PhonePe", "Swiggy", "Zomato", "Paytm", "Dream11"],
        "top_companies_global": ["Google", "Apple", "Meta", "Uber", "Airbnb"],
        "market_demand": "HIGH",
        "growth_potential": "High — mobile-first India",
        "certifications": ["Google Associate Android Developer", "Flutter Certification"],
        "roadmap": [
            {"step": 1, "title": "Dart & Flutter Basics", "description": "Learn Dart language and Flutter framework", "duration": "2-3 months"},
            {"step": 2, "title": "UI & State Management", "description": "Material Design, Provider/Riverpod/Bloc", "duration": "2 months"},
            {"step": 3, "title": "APIs & Backend", "description": "REST API integration, Firebase, local storage", "duration": "2 months"},
            {"step": 4, "title": "Publish Apps", "description": "Build and publish 2-3 apps on Play Store", "duration": "2-3 months"},
            {"step": 5, "title": "Advanced Topics", "description": "Animations, platform channels, testing, CI/CD", "duration": "Ongoing"},
        ],
        "keywords": ["mobile", "app", "android", "ios", "flutter", "react native", "dart"],
        "related_careers": ["Full Stack Developer", "UI/UX Designer"],
    },
    # ─── 10 Blockchain Developer ───────────────────────
    {
        "title": "Blockchain Developer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Build decentralized applications and smart contracts. Emerging field in India with growing fintech and Web3 adoption.",
        "required_skills": ["Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Cryptography", "JavaScript", "Node.js", "DeFi concepts"],
        "recommended_subjects": ["Cryptography & Network Security", "Data Structures and Algorithms", "Computer Networks"],
        "recommended_electives": ["Blockchain Technology"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Blockchain Developer", "Smart Contract Developer", "Web3 Developer", "DeFi Engineer"],
        "salary_range": {"entry_level": "6-12 LPA", "mid_level": "15-30 LPA", "senior_level": "30-60 LPA", "top_companies": "35-80+ LPA"},
        "top_companies_india": ["Polygon (Matic)", "CoinDCX", "WazirX", "Zerodha (Crypto)", "Binance India"],
        "top_companies_global": ["Consensys", "Chainlink", "Alchemy", "Coinbase", "Binance"],
        "market_demand": "EMERGING",
        "growth_potential": "High — Web3 and DeFi are growing rapidly",
        "certifications": ["Certified Blockchain Developer", "Ethereum Developer Certification"],
        "roadmap": [
            {"step": 1, "title": "Blockchain Fundamentals", "description": "Understand distributed ledger, consensus, hashing", "duration": "1-2 months"},
            {"step": 2, "title": "Solidity & Smart Contracts", "description": "Write and deploy smart contracts on Ethereum", "duration": "3 months"},
            {"step": 3, "title": "DApp Development", "description": "Build frontend with Web3.js/ethers.js", "duration": "2-3 months"},
            {"step": 4, "title": "DeFi & Advanced", "description": "Token standards, DeFi protocols, Layer-2 solutions", "duration": "3 months"},
            {"step": 5, "title": "Hackathons & Contribute", "description": "Participate in ETH hackathons, contribute to open-source", "duration": "Ongoing"},
        ],
        "keywords": ["blockchain", "web3", "smart contract", "ethereum", "solidity", "defi", "crypto", "decentralized"],
        "related_careers": ["Software Developer", "Cybersecurity Analyst"],
    },
    # ─── 11 IoT Developer ──────────────────────────────
    {
        "title": "IoT Developer",
        "category": "NETWORKING_AND_IOT",
        "description": "Build connected device ecosystems combining hardware and software. Growing rapidly with India's smart city and Industry 4.0 initiatives.",
        "required_skills": ["Embedded C", "Python", "MQTT", "Raspberry Pi", "Arduino", "Cloud IoT", "Sensors", "Edge Computing"],
        "recommended_subjects": ["Microcontroller & Embedded Systems", "Computer Networks", "Digital Logic & Design"],
        "recommended_electives": ["Internet of Things", "Edge Computing"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["IoT Developer", "Embedded Systems Engineer", "IoT Solutions Architect"],
        "salary_range": {"entry_level": "4-7 LPA", "mid_level": "8-16 LPA", "senior_level": "16-30 LPA", "top_companies": "20-40 LPA"},
        "top_companies_india": ["Bosch India", "Samsung R&D", "Tata Elxsi", "L&T Technology", "Honeywell India"],
        "top_companies_global": ["Siemens", "Bosch", "Cisco", "Intel", "AWS IoT"],
        "market_demand": "HIGH",
        "growth_potential": "High — Smart cities, Industry 4.0, connected vehicles",
        "certifications": ["AWS IoT Core", "Cisco IoT Fundamentals"],
        "roadmap": [
            {"step": 1, "title": "Microcontroller Basics", "description": "Arduino, ESP32, basic sensor interfacing", "duration": "2 months"},
            {"step": 2, "title": "Communication Protocols", "description": "MQTT, HTTP, BLE, LoRa, WiFi", "duration": "2 months"},
            {"step": 3, "title": "Cloud Integration", "description": "AWS IoT, Azure IoT Hub, data pipelines", "duration": "2-3 months"},
            {"step": 4, "title": "Edge Computing", "description": "TensorFlow Lite, edge ML, real-time processing", "duration": "2-3 months"},
            {"step": 5, "title": "Projects", "description": "Build smart home or environmental monitoring system", "duration": "Ongoing"},
        ],
        "keywords": ["iot", "internet of things", "embedded", "sensors", "raspberry pi", "arduino", "edge computing"],
        "related_careers": ["Embedded Systems Engineer", "Cloud Architect"],
    },
    # ─── 12 Product Manager (Tech) ─────────────────────
    {
        "title": "Product Manager (Tech)",
        "category": "MANAGEMENT",
        "description": "Drive product strategy and execution. Bridges business, design, and engineering. Popular career pivot for engineers at top Indian startups.",
        "required_skills": ["Product Thinking", "Data Analysis", "SQL", "Wireframing", "A/B Testing", "Agile/Scrum", "Communication", "User Research"],
        "recommended_subjects": ["Software Engineering", "Database Management Systems", "Data Structures and Algorithms"],
        "recommended_electives": ["Project Management", "Business Analytics", "Entrepreneurship Development"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Associate Product Manager", "Product Manager", "Senior PM", "Group PM", "VP Product"],
        "salary_range": {"entry_level": "8-15 LPA", "mid_level": "18-35 LPA", "senior_level": "35-60 LPA", "top_companies": "40-1Cr+ LPA"},
        "top_companies_india": ["Flipkart", "Swiggy", "CRED", "Razorpay", "PhonePe", "Meesho", "Dream11"],
        "top_companies_global": ["Google", "Meta", "Amazon", "Microsoft", "Stripe"],
        "market_demand": "HIGH",
        "growth_potential": "Very High — every tech company needs strong PMs",
        "certifications": ["Google PM Certificate", "Product School Certification", "Pragmatic Institute"],
        "roadmap": [
            {"step": 1, "title": "Build Technical Foundation", "description": "Strong coding + system design understanding", "duration": "During college"},
            {"step": 2, "title": "Learn Product Frameworks", "description": "Study PRDs, user stories, RICE/ICE, jobs-to-be-done", "duration": "2-3 months"},
            {"step": 3, "title": "Data & Analytics", "description": "SQL, metrics, A/B testing, funnel analysis", "duration": "2 months"},
            {"step": 4, "title": "Build & Ship a Product", "description": "Create a side project, get real users, iterate", "duration": "3-4 months"},
            {"step": 5, "title": "APM Programs", "description": "Apply to Google APM, Flipkart APM, Razorpay APM", "duration": "Final year"},
        ],
        "keywords": ["product manager", "pm", "product", "apm", "strategy", "management", "business"],
        "related_careers": ["Business Analyst", "Software Developer", "Data Analyst"],
    },
    # ─── 13 AI Research Engineer ────────────────────────
    {
        "title": "AI Research Engineer",
        "category": "DATA_AND_AI",
        "description": "Push the boundaries of artificial intelligence through novel research and implementation. Requires strong mathematical foundations and research aptitude.",
        "required_skills": ["Python", "PyTorch/TensorFlow", "Linear Algebra", "Probability", "NLP/CV", "Research Paper Reading", "Experiment Design", "LaTeX"],
        "recommended_subjects": ["Engineering Mathematics-III", "Engineering Mathematics-IV", "Artificial Intelligence", "Design & Analysis of Algorithms"],
        "recommended_electives": ["Deep Learning", "Natural Language Processing", "Quantum Computing"],
        "min_cgpa_recommended": 8.0,
        "job_titles": ["AI Research Engineer", "Research Scientist", "Applied Researcher", "ML Research Intern"],
        "salary_range": {"entry_level": "10-18 LPA", "mid_level": "20-40 LPA", "senior_level": "40-80 LPA", "top_companies": "50-1.5Cr+ LPA"},
        "top_companies_india": ["Google Research India", "Microsoft Research India", "Samsung R&D", "IBM Research", "TCS Research"],
        "top_companies_global": ["Google DeepMind", "OpenAI", "Meta FAIR", "Anthropic", "NVIDIA Research"],
        "market_demand": "HIGH",
        "growth_potential": "Very High — AI research defines the future of technology",
        "certifications": ["Deep Learning Specialization (Coursera)", "Stanford CS229/CS231n (audit)"],
        "roadmap": [
            {"step": 1, "title": "Mathematics Deep Dive", "description": "Linear algebra, probability, optimization, information theory", "duration": "4-6 months"},
            {"step": 2, "title": "ML/DL Mastery", "description": "Implement papers from scratch, understand architectures", "duration": "6 months"},
            {"step": 3, "title": "Research Skills", "description": "Read 50+ papers, reproduce results, identify gaps", "duration": "6 months"},
            {"step": 4, "title": "Publish", "description": "Work on novel ideas, submit to conferences (NeurIPS, ICML, AAAI)", "duration": "6-12 months"},
            {"step": 5, "title": "MS/PhD or Research Lab", "description": "Consider MS/PhD at top universities or join research labs", "duration": "2-5 years"},
        ],
        "keywords": ["ai research", "research scientist", "deep learning research", "nlp research", "computer vision research", "phd"],
        "related_careers": ["Data Scientist", "ML Engineer", "NLP Engineer"],
    },
    # ─── 14 Network Engineer ────────────────────────────
    {
        "title": "Network Engineer",
        "category": "NETWORKING_AND_IOT",
        "description": "Design, implement, and manage computer networks. Foundational IT role with strong demand in India's growing enterprise and telecom sectors.",
        "required_skills": ["TCP/IP", "Routing & Switching", "Cisco IOS", "Firewalls", "VPN", "DNS/DHCP", "Linux", "Network Monitoring"],
        "recommended_subjects": ["Computer Networks", "Operating Systems", "Cryptography & Network Security"],
        "recommended_electives": ["Wireless Technology", "Cloud Computing Services"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Network Engineer", "Network Administrator", "NOC Engineer", "Network Architect"],
        "salary_range": {"entry_level": "3-6 LPA", "mid_level": "7-15 LPA", "senior_level": "15-30 LPA", "top_companies": "18-40 LPA"},
        "top_companies_india": ["Cisco India", "Jio", "Airtel", "TCS", "Wipro", "HCL", "Juniper India"],
        "top_companies_global": ["Cisco", "Juniper Networks", "Arista", "Palo Alto Networks"],
        "market_demand": "HIGH",
        "growth_potential": "Stable — evolving towards SDN and cloud networking",
        "certifications": ["CCNA", "CCNP", "CompTIA Network+", "Juniper JNCIA"],
        "roadmap": [
            {"step": 1, "title": "Networking Basics", "description": "OSI model, TCP/IP, subnetting, VLANs", "duration": "2-3 months"},
            {"step": 2, "title": "Cisco / Juniper", "description": "Router/switch configuration, OSPF, BGP", "duration": "3 months"},
            {"step": 3, "title": "Security Basics", "description": "Firewalls, ACLs, VPN, IDS/IPS", "duration": "2 months"},
            {"step": 4, "title": "CCNA Certification", "description": "Study and pass Cisco CCNA 200-301", "duration": "3-4 months"},
            {"step": 5, "title": "Cloud Networking", "description": "AWS VPC, Azure Networking, SDN concepts", "duration": "2-3 months"},
        ],
        "keywords": ["network", "networking", "cisco", "ccna", "router", "switch", "telecom", "infrastructure"],
        "related_careers": ["Cybersecurity Analyst", "Cloud Architect", "DevOps Engineer"],
    },
    # ─── 15 UI/UX Designer ─────────────────────────────
    {
        "title": "UI/UX Designer",
        "category": "DESIGN",
        "description": "Design user interfaces and experiences for digital products. Growing role in India as companies focus on user-centric design.",
        "required_skills": ["Figma", "Adobe XD", "User Research", "Wireframing", "Prototyping", "Design Systems", "HTML/CSS", "Usability Testing"],
        "recommended_subjects": ["Software Engineering", "Database Management Systems"],
        "recommended_electives": ["AR/VR Technologies", "Digital Marketing"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["UI Designer", "UX Designer", "Product Designer", "Interaction Designer", "UX Researcher"],
        "salary_range": {"entry_level": "3-7 LPA", "mid_level": "8-18 LPA", "senior_level": "18-35 LPA", "top_companies": "20-50+ LPA"},
        "top_companies_india": ["CRED", "Swiggy", "Flipkart", "Razorpay", "Freshworks", "Zomato"],
        "top_companies_global": ["Apple", "Google", "Airbnb", "Figma", "Spotify"],
        "market_demand": "HIGH",
        "growth_potential": "High — design-led companies outperform competitors",
        "certifications": ["Google UX Design Certificate", "Interaction Design Foundation"],
        "roadmap": [
            {"step": 1, "title": "Design Fundamentals", "description": "Typography, color theory, layout, visual hierarchy", "duration": "2 months"},
            {"step": 2, "title": "Tool Mastery", "description": "Figma (primary), Adobe XD, prototyping tools", "duration": "2 months"},
            {"step": 3, "title": "UX Research", "description": "User interviews, personas, journey maps, usability testing", "duration": "2-3 months"},
            {"step": 4, "title": "Design Systems", "description": "Component libraries, style guides, accessibility", "duration": "2 months"},
            {"step": 5, "title": "Portfolio", "description": "Build 4-5 case studies showing process and outcomes", "duration": "Ongoing"},
        ],
        "keywords": ["ui", "ux", "design", "user interface", "user experience", "figma", "product design", "designer"],
        "related_careers": ["Full Stack Developer", "Product Manager"],
    },
    # ─── 16 QA / Test Automation Engineer ───────────────
    {
        "title": "QA / Test Automation Engineer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Ensure software quality through automated and manual testing. Strong demand in India's IT services and product companies.",
        "required_skills": ["Selenium", "Python/Java", "API Testing", "CI/CD", "JIRA", "SQL", "Performance Testing", "Test Frameworks"],
        "recommended_subjects": ["Software Engineering", "Data Structures and Algorithms", "Database Management Systems"],
        "recommended_electives": ["Software Testing", "DevOps Laboratory"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["QA Engineer", "SDET", "Test Automation Engineer", "Quality Analyst"],
        "salary_range": {"entry_level": "3-6 LPA", "mid_level": "7-15 LPA", "senior_level": "15-28 LPA", "top_companies": "18-40 LPA"},
        "top_companies_india": ["TCS", "Infosys", "Cognizant", "Accenture", "Flipkart", "Freshworks"],
        "top_companies_global": ["Google", "Microsoft", "Amazon", "Apple"],
        "market_demand": "HIGH",
        "growth_potential": "High — shift-left testing and SDET roles growing",
        "certifications": ["ISTQB Foundation", "Selenium Certification", "AWS Certified Cloud Practitioner"],
        "roadmap": [
            {"step": 1, "title": "Testing Fundamentals", "description": "Test types, STLC, bug lifecycle, test cases", "duration": "1-2 months"},
            {"step": 2, "title": "Programming", "description": "Python or Java for test automation", "duration": "2-3 months"},
            {"step": 3, "title": "Selenium & Frameworks", "description": "Selenium WebDriver, TestNG/PyTest, Page Object Model", "duration": "2-3 months"},
            {"step": 4, "title": "API & Performance Testing", "description": "Postman, REST Assured, JMeter, k6", "duration": "2 months"},
            {"step": 5, "title": "CI/CD Integration", "description": "Jenkins/GitHub Actions, Docker, test pipelines", "duration": "2 months"},
        ],
        "keywords": ["qa", "testing", "automation", "sdet", "quality", "selenium", "test engineer"],
        "related_careers": ["Software Developer", "DevOps Engineer"],
    },
    # ─── 17 NLP Engineer ───────────────────────────────
    {
        "title": "NLP Engineer",
        "category": "DATA_AND_AI",
        "description": "Build systems that understand and generate human language. Booming field with ChatGPT, voice assistants, and multilingual India.",
        "required_skills": ["Python", "NLP Libraries (spaCy, NLTK, HuggingFace)", "Transformers", "Deep Learning", "Text Processing", "LLMs", "Prompt Engineering"],
        "recommended_subjects": ["Artificial Intelligence", "Engineering Mathematics-III", "Python Programming"],
        "recommended_electives": ["Natural Language Processing", "Deep Learning"],
        "min_cgpa_recommended": 7.5,
        "job_titles": ["NLP Engineer", "Conversational AI Developer", "LLM Engineer", "Language AI Researcher"],
        "salary_range": {"entry_level": "8-14 LPA", "mid_level": "15-30 LPA", "senior_level": "30-55 LPA", "top_companies": "40-80+ LPA"},
        "top_companies_india": ["Google India", "Microsoft India", "Flipkart", "Haptik", "Yellow.ai", "Krutrim"],
        "top_companies_global": ["OpenAI", "Google", "Meta", "Anthropic", "Cohere"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — LLMs and GenAI are the biggest tech trend",
        "certifications": ["HuggingFace NLP Course (free)", "DeepLearning.AI NLP Specialization"],
        "roadmap": [
            {"step": 1, "title": "NLP Basics", "description": "Tokenization, stemming, POS tagging, Named Entity Recognition", "duration": "2 months"},
            {"step": 2, "title": "Classical NLP", "description": "TF-IDF, Word2Vec, sentiment analysis, text classification", "duration": "2-3 months"},
            {"step": 3, "title": "Transformers", "description": "Attention mechanism, BERT, GPT, T5 architectures", "duration": "3 months"},
            {"step": 4, "title": "LLM Applications", "description": "Fine-tuning, RAG, prompt engineering, LangChain", "duration": "3 months"},
            {"step": 5, "title": "Build & Deploy", "description": "Build chatbots, Q&A systems, deploy with APIs", "duration": "Ongoing"},
        ],
        "keywords": ["nlp", "natural language processing", "chatbot", "llm", "gpt", "transformers", "language model", "conversational ai"],
        "related_careers": ["ML Engineer", "AI Research Engineer", "Data Scientist"],
    },
    # ─── 18 Business Analyst ───────────────────────────
    {
        "title": "Business Analyst",
        "category": "MANAGEMENT",
        "description": "Analyze business processes and recommend improvements using data and technology. Strong bridge role between business and IT teams.",
        "required_skills": ["Requirements Analysis", "SQL", "Excel", "JIRA", "Process Mapping", "UML Diagrams", "Communication", "Agile"],
        "recommended_subjects": ["Software Engineering", "Database Management Systems"],
        "recommended_electives": ["Project Management", "Business Analytics", "Entrepreneurship Development"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Business Analyst", "Systems Analyst", "IT Business Analyst", "Functional Consultant"],
        "salary_range": {"entry_level": "4-7 LPA", "mid_level": "8-16 LPA", "senior_level": "16-30 LPA", "top_companies": "18-40 LPA"},
        "top_companies_india": ["Deloitte", "EY", "KPMG", "Accenture", "Capgemini", "TCS"],
        "top_companies_global": ["McKinsey", "BCG", "Bain", "Accenture"],
        "market_demand": "HIGH",
        "growth_potential": "High — digital transformation needs analysts",
        "certifications": ["CBAP", "PMI-PBA", "Six Sigma Green Belt"],
        "roadmap": [
            {"step": 1, "title": "BA Fundamentals", "description": "Requirements elicitation, BRD/SRS, stakeholder management", "duration": "2 months"},
            {"step": 2, "title": "Data & SQL", "description": "SQL for analysis, Excel advanced features, Power BI", "duration": "2-3 months"},
            {"step": 3, "title": "Process Modeling", "description": "BPMN, UML, use cases, user stories", "duration": "2 months"},
            {"step": 4, "title": "Agile & Tools", "description": "Scrum, Kanban, JIRA, Confluence", "duration": "1-2 months"},
            {"step": 5, "title": "Domain Knowledge", "description": "Pick a domain (fintech, healthcare, e-commerce)", "duration": "Ongoing"},
        ],
        "keywords": ["business analyst", "ba", "requirements", "process", "consulting", "systems analyst"],
        "related_careers": ["Product Manager", "Data Analyst", "Project Manager"],
    },
    # ─── 19 Game Developer ─────────────────────────────
    {
        "title": "Game Developer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Design and build video games and interactive experiences. Combines programming, creativity, and physics simulation. India's gaming industry is growing rapidly.",
        "required_skills": ["Unity/Unreal Engine", "C#/C++", "Game Physics", "3D Math", "Shader Programming", "Version Control", "Game Design Patterns", "Multiplayer Networking"],
        "recommended_subjects": ["Data Structures and Algorithms", "Engineering Mathematics-III", "Computer Graphics", "Operating Systems"],
        "recommended_electives": ["AR/VR Technologies", "Multimedia Computing"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Game Developer", "Game Programmer", "Unity Developer", "Unreal Developer", "Gameplay Engineer"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "10-22 LPA", "senior_level": "22-45 LPA", "top_companies": "25-60+ LPA"},
        "top_companies_india": ["Ubisoft India", "Zynga India", "Rockstar India", "Games2Win", "Dream11", "nCore Games"],
        "top_companies_global": ["Nintendo", "Riot Games", "Epic Games", "Valve", "Blizzard"],
        "market_demand": "HIGH",
        "growth_potential": "High — Indian gaming market projected $8.6B by 2027",
        "certifications": ["Unity Certified Developer", "Unreal Authorized Instructor"],
        "roadmap": [
            {"step": 1, "title": "C# & Unity Basics", "description": "Learn C# programming and Unity engine fundamentals", "duration": "3 months"},
            {"step": 2, "title": "Game Mechanics", "description": "Physics, collisions, input handling, UI systems", "duration": "2-3 months"},
            {"step": 3, "title": "2D & 3D Development", "description": "Build complete 2D and 3D games with levels and AI", "duration": "3-4 months"},
            {"step": 4, "title": "Multiplayer & Networking", "description": "Photon, Mirror, or Netcode for GameObjects", "duration": "2-3 months"},
            {"step": 5, "title": "Publish & Portfolio", "description": "Ship games on Steam/itch.io, build portfolio", "duration": "Ongoing"},
        ],
        "keywords": ["game", "gaming", "unity", "unreal", "game developer", "game design", "game engine", "3d", "gameplay"],
        "related_careers": ["Software Developer", "AR/VR Engineer", "UI/UX Designer"],
    },
    # ─── 20 AR/VR Engineer ─────────────────────────────
    {
        "title": "AR/VR Engineer",
        "category": "SOFTWARE_DEVELOPMENT",
        "description": "Build augmented and virtual reality experiences for gaming, education, healthcare, and enterprise. Rapidly growing with Apple Vision Pro and Meta Quest.",
        "required_skills": ["Unity/Unreal", "C#/C++", "3D Mathematics", "Spatial Computing", "OpenXR", "ARCore/ARKit", "Computer Vision", "Shader Programming"],
        "recommended_subjects": ["Computer Graphics", "Engineering Mathematics-III", "Data Structures and Algorithms", "Artificial Intelligence"],
        "recommended_electives": ["AR/VR Technologies", "Multimedia Computing"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["AR/VR Developer", "XR Engineer", "Spatial Computing Engineer", "Metaverse Developer"],
        "salary_range": {"entry_level": "6-12 LPA", "mid_level": "14-28 LPA", "senior_level": "28-50 LPA", "top_companies": "30-70+ LPA"},
        "top_companies_india": ["Infosys XR Lab", "TCS Innovation", "Flipkart XR", "Reliance Jio", "PTC India"],
        "top_companies_global": ["Meta Reality Labs", "Apple Vision", "Microsoft HoloLens", "Niantic", "Unity"],
        "market_demand": "EMERGING",
        "growth_potential": "Very High — spatial computing is the next platform shift",
        "certifications": ["Unity XR Developer", "Meta Spark Developer"],
        "roadmap": [
            {"step": 1, "title": "3D Math & Graphics", "description": "Vectors, quaternions, transformations, rendering pipeline", "duration": "2-3 months"},
            {"step": 2, "title": "Unity XR Toolkit", "description": "VR interactions, hand tracking, spatial UI", "duration": "3 months"},
            {"step": 3, "title": "AR Development", "description": "ARCore/ARKit, plane detection, object placement", "duration": "2-3 months"},
            {"step": 4, "title": "Advanced Topics", "description": "Passthrough, eye tracking, spatial anchors, multiplayer XR", "duration": "3 months"},
            {"step": 5, "title": "Portfolio Projects", "description": "Build immersive experiences, publish on Meta Store", "duration": "Ongoing"},
        ],
        "keywords": ["ar", "vr", "augmented reality", "virtual reality", "xr", "mixed reality", "metaverse", "spatial computing", "hololens"],
        "related_careers": ["Game Developer", "Software Developer", "UI/UX Designer"],
    },
    # ─── 21 Embedded Systems Engineer ──────────────────
    {
        "title": "Embedded Systems Engineer",
        "category": "NETWORKING_AND_IOT",
        "description": "Design firmware and software for embedded devices — from automotive ECUs to medical devices. Strong demand in India's growing hardware ecosystem.",
        "required_skills": ["C/C++", "RTOS", "Microcontrollers (ARM, AVR)", "I2C/SPI/UART", "PCB Basics", "Debugging Tools", "Linux Kernel", "Device Drivers"],
        "recommended_subjects": ["Microcontroller & Embedded Systems", "Digital Logic & Design", "Computer Organization & Architecture", "Operating Systems"],
        "recommended_electives": ["Internet of Things", "VLSI Design"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Embedded Software Engineer", "Firmware Engineer", "Embedded Systems Developer", "RTOS Developer"],
        "salary_range": {"entry_level": "4-8 LPA", "mid_level": "8-18 LPA", "senior_level": "18-35 LPA", "top_companies": "20-50 LPA"},
        "top_companies_india": ["Qualcomm India", "Texas Instruments India", "Samsung R&D", "Bosch India", "Continental India", "Tata Elxsi"],
        "top_companies_global": ["Intel", "Qualcomm", "NXP", "STMicroelectronics", "Tesla Firmware"],
        "market_demand": "HIGH",
        "growth_potential": "High — automotive, medical, and consumer electronics growth",
        "certifications": ["ARM Certified Engineer", "Embedded Linux Professional"],
        "roadmap": [
            {"step": 1, "title": "C Programming Mastery", "description": "Pointers, memory management, bit manipulation", "duration": "2-3 months"},
            {"step": 2, "title": "Microcontroller Programming", "description": "ARM Cortex-M, GPIO, timers, interrupts, ADC", "duration": "3 months"},
            {"step": 3, "title": "RTOS & Protocols", "description": "FreeRTOS, I2C, SPI, UART, CAN bus", "duration": "2-3 months"},
            {"step": 4, "title": "Embedded Linux", "description": "Yocto, device drivers, kernel modules", "duration": "3-4 months"},
            {"step": 5, "title": "Industry Projects", "description": "Build real hardware projects, contribute to open-source", "duration": "Ongoing"},
        ],
        "keywords": ["embedded", "firmware", "microcontroller", "arm", "rtos", "hardware", "drivers", "low level"],
        "related_careers": ["IoT Developer", "Network Engineer"],
    },
    # ─── 22 Database Administrator ─────────────────────
    {
        "title": "Database Administrator",
        "category": "DATA_AND_AI",
        "description": "Manage, optimize, and secure database systems. Essential role for any data-heavy organization. High demand in banking, e-commerce, and enterprise IT.",
        "required_skills": ["SQL", "PostgreSQL/MySQL", "MongoDB", "Oracle", "Database Tuning", "Backup & Recovery", "Replication", "Cloud Databases"],
        "recommended_subjects": ["Database Management Systems", "Operating Systems", "Data Structures and Algorithms"],
        "recommended_electives": ["Data Warehouse and Mining", "Cloud Computing Services"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Database Administrator", "DBA", "Database Engineer", "Data Platform Engineer"],
        "salary_range": {"entry_level": "4-7 LPA", "mid_level": "8-18 LPA", "senior_level": "18-35 LPA", "top_companies": "20-45 LPA"},
        "top_companies_india": ["Oracle India", "TCS", "Infosys", "Amazon India", "Flipkart", "HDFC Bank"],
        "top_companies_global": ["Oracle", "Amazon RDS", "Google Cloud SQL", "MongoDB Inc", "Snowflake"],
        "market_demand": "HIGH",
        "growth_potential": "Stable — evolving towards cloud-native data platforms",
        "certifications": ["Oracle Database Administrator", "MongoDB Certified DBA", "AWS Database Specialty"],
        "roadmap": [
            {"step": 1, "title": "SQL Mastery", "description": "Complex queries, stored procedures, indexing strategies", "duration": "2-3 months"},
            {"step": 2, "title": "RDBMS Deep Dive", "description": "PostgreSQL or Oracle — internals, tuning, explain plans", "duration": "3 months"},
            {"step": 3, "title": "NoSQL Databases", "description": "MongoDB, Redis, Cassandra — when to use what", "duration": "2 months"},
            {"step": 4, "title": "Administration", "description": "Backup, replication, sharding, security, monitoring", "duration": "3 months"},
            {"step": 5, "title": "Cloud Databases", "description": "AWS RDS, Aurora, DynamoDB, Azure CosmosDB", "duration": "2-3 months"},
        ],
        "keywords": ["database", "dba", "database administrator", "sql", "oracle", "postgres", "mongodb", "data platform"],
        "related_careers": ["Data Engineer", "Software Developer", "Cloud Architect"],
    },
    # ─── 23 Technical Writer ───────────────────────────
    {
        "title": "Technical Writer",
        "category": "MANAGEMENT",
        "description": "Create documentation, API references, tutorials, and developer guides. Underrated career with good work-life balance and growing demand in tech companies.",
        "required_skills": ["Technical Writing", "Markdown/RST", "API Documentation", "Git", "Docs-as-Code", "Information Architecture", "Diagrams (Mermaid/PlantUML)", "Basic Coding"],
        "recommended_subjects": ["Software Engineering", "Computer Networks", "Database Management Systems"],
        "recommended_electives": ["Project Management", "Business Analytics"],
        "min_cgpa_recommended": 6.0,
        "job_titles": ["Technical Writer", "Documentation Engineer", "Developer Advocate", "Content Developer"],
        "salary_range": {"entry_level": "4-7 LPA", "mid_level": "8-16 LPA", "senior_level": "16-28 LPA", "top_companies": "18-40 LPA"},
        "top_companies_india": ["Google India", "Microsoft India", "Zoho", "Freshworks", "Razorpay"],
        "top_companies_global": ["Google", "Microsoft", "Stripe", "Twilio", "GitLab"],
        "market_demand": "MODERATE",
        "growth_potential": "Moderate — API economy drives docs demand",
        "certifications": ["Google Technical Writing Certificate", "Society for Technical Communication"],
        "roadmap": [
            {"step": 1, "title": "Writing Fundamentals", "description": "Technical writing principles, clarity, structure", "duration": "1-2 months"},
            {"step": 2, "title": "Tools & Workflows", "description": "Markdown, Git, static site generators (Docusaurus, MkDocs)", "duration": "2 months"},
            {"step": 3, "title": "API Documentation", "description": "OpenAPI/Swagger, REST docs, code samples", "duration": "2 months"},
            {"step": 4, "title": "Build Portfolio", "description": "Write docs for open-source projects, create tutorials", "duration": "2-3 months"},
            {"step": 5, "title": "Dev Relations", "description": "Blog posts, conference talks, community building", "duration": "Ongoing"},
        ],
        "keywords": ["technical writer", "documentation", "api docs", "developer advocate", "content", "writing"],
        "related_careers": ["Software Developer", "Product Manager"],
    },
    # ─── 24 Data Engineer ──────────────────────────────
    {
        "title": "Data Engineer",
        "category": "DATA_AND_AI",
        "description": "Build and maintain data pipelines, warehouses, and ETL systems. The backbone of any data team — ensures data scientists have clean, reliable data.",
        "required_skills": ["Python", "SQL", "Apache Spark", "Airflow", "Kafka", "Data Warehousing", "ETL/ELT", "Cloud Data Services", "dbt"],
        "recommended_subjects": ["Database Management Systems", "Data Structures and Algorithms", "Operating Systems"],
        "recommended_electives": ["Big Data Analytics", "Data Warehouse and Mining", "Cloud Computing Services"],
        "min_cgpa_recommended": 6.5,
        "job_titles": ["Data Engineer", "ETL Developer", "Big Data Engineer", "Data Platform Engineer", "Analytics Engineer"],
        "salary_range": {"entry_level": "6-10 LPA", "mid_level": "12-25 LPA", "senior_level": "25-45 LPA", "top_companies": "30-65+ LPA"},
        "top_companies_india": ["Flipkart", "Amazon India", "Swiggy", "PhonePe", "Razorpay", "Jio"],
        "top_companies_global": ["Netflix", "Spotify", "Uber", "Airbnb", "Snowflake"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — data infrastructure is critical for every company",
        "certifications": ["Databricks Data Engineer", "AWS Data Analytics Specialty", "Google Cloud Data Engineer"],
        "roadmap": [
            {"step": 1, "title": "SQL & Python", "description": "Advanced SQL, Python data manipulation, scripting", "duration": "2-3 months"},
            {"step": 2, "title": "Data Warehousing", "description": "Star/snowflake schema, dimensional modeling, dbt", "duration": "2-3 months"},
            {"step": 3, "title": "Big Data Tools", "description": "Apache Spark, Kafka, Flink fundamentals", "duration": "3 months"},
            {"step": 4, "title": "Orchestration & Cloud", "description": "Airflow, AWS Glue, Redshift, BigQuery, Snowflake", "duration": "3 months"},
            {"step": 5, "title": "Production Pipelines", "description": "Build end-to-end pipelines, monitoring, data quality", "duration": "Ongoing"},
        ],
        "keywords": ["data engineer", "etl", "data pipeline", "spark", "airflow", "data warehouse", "big data", "kafka"],
        "related_careers": ["Data Scientist", "Database Administrator", "ML Engineer"],
    },
    # ─── 25 Site Reliability Engineer ──────────────────
    {
        "title": "Site Reliability Engineer (SRE)",
        "category": "CLOUD_AND_DEVOPS",
        "description": "Keep production systems running reliably at scale. Combines software engineering with operations. Google-pioneered role now adopted across India's top tech companies.",
        "required_skills": ["Linux", "Python/Go", "Monitoring (Prometheus/Grafana)", "Incident Management", "SLOs/SLIs", "Kubernetes", "Cloud Platforms", "Distributed Systems"],
        "recommended_subjects": ["Operating Systems", "Computer Networks", "Data Structures and Algorithms", "Software Engineering"],
        "recommended_electives": ["Cloud Computing Services"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Site Reliability Engineer", "SRE", "Production Engineer", "Reliability Engineer", "Infrastructure Engineer"],
        "salary_range": {"entry_level": "8-14 LPA", "mid_level": "16-30 LPA", "senior_level": "30-55 LPA", "top_companies": "35-75+ LPA"},
        "top_companies_india": ["Google India", "Microsoft India", "Flipkart", "Razorpay", "PhonePe", "Dream11"],
        "top_companies_global": ["Google", "LinkedIn", "Netflix", "Uber", "Cloudflare"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — every major tech company has SRE teams",
        "certifications": ["Google SRE Workbook (free)", "AWS DevOps Professional", "Kubernetes CKA"],
        "roadmap": [
            {"step": 1, "title": "Software Engineering", "description": "Strong coding skills in Python or Go, data structures", "duration": "3-4 months"},
            {"step": 2, "title": "Linux & Systems", "description": "Deep Linux knowledge, networking, system calls, troubleshooting", "duration": "3 months"},
            {"step": 3, "title": "Monitoring & Observability", "description": "Prometheus, Grafana, ELK, distributed tracing", "duration": "2-3 months"},
            {"step": 4, "title": "SRE Practices", "description": "SLOs, error budgets, toil reduction, incident management", "duration": "2 months"},
            {"step": 5, "title": "Distributed Systems", "description": "Consensus, replication, partitioning, chaos engineering", "duration": "Ongoing"},
        ],
        "keywords": ["sre", "site reliability", "reliability", "production", "on-call", "monitoring", "incident", "observability"],
        "related_careers": ["DevOps Engineer", "Cloud Architect", "Software Developer"],
    },
    # ─── 26 Solutions Architect ────────────────────────
    {
        "title": "Solutions Architect",
        "category": "CLOUD_AND_DEVOPS",
        "description": "Design end-to-end technical solutions for complex business problems. Senior role bridging business requirements with technical architecture.",
        "required_skills": ["System Design", "Cloud Architecture", "Microservices", "API Design", "Security", "Cost Optimization", "Stakeholder Communication", "Multi-Cloud"],
        "recommended_subjects": ["Computer Networks", "Software Engineering", "Database Management Systems", "Operating Systems"],
        "recommended_electives": ["Cloud Computing Services", "Enterprise Resource Planning"],
        "min_cgpa_recommended": 7.0,
        "job_titles": ["Solutions Architect", "Technical Architect", "Enterprise Architect", "Cloud Solutions Architect"],
        "salary_range": {"entry_level": "10-16 LPA", "mid_level": "18-35 LPA", "senior_level": "35-65 LPA", "top_companies": "40-1Cr+ LPA"},
        "top_companies_india": ["Amazon India", "Microsoft India", "Google Cloud India", "Deloitte", "Accenture"],
        "top_companies_global": ["AWS", "Azure", "Google Cloud", "Salesforce", "ServiceNow"],
        "market_demand": "VERY_HIGH",
        "growth_potential": "Very High — critical for enterprise cloud adoption",
        "certifications": ["AWS Solutions Architect Professional", "Azure Solutions Architect Expert", "TOGAF"],
        "roadmap": [
            {"step": 1, "title": "Software Development", "description": "5+ years of hands-on development experience", "duration": "3-5 years"},
            {"step": 2, "title": "System Design", "description": "Distributed systems, scalability patterns, trade-offs", "duration": "6 months"},
            {"step": 3, "title": "Cloud Mastery", "description": "Deep expertise in at least one cloud platform", "duration": "6-12 months"},
            {"step": 4, "title": "Architecture Frameworks", "description": "Well-Architected Framework, TOGAF, microservices patterns", "duration": "3-6 months"},
            {"step": 5, "title": "Leadership & Communication", "description": "White-boarding, tech talks, stakeholder management", "duration": "Ongoing"},
        ],
        "keywords": ["solutions architect", "architect", "system design", "enterprise", "technical architect", "cloud architect"],
        "related_careers": ["Cloud Architect", "DevOps Engineer", "Software Developer"],
    },
    # ─── 27 Quantitative Analyst / FinTech ─────────────
    {
        "title": "Quantitative Analyst (FinTech)",
        "category": "DATA_AND_AI",
        "description": "Apply mathematical models and algorithms to financial markets. High-paying role combining strong math with programming. India's FinTech sector is booming.",
        "required_skills": ["Python/R", "Statistics", "Stochastic Calculus", "Time Series Analysis", "Machine Learning", "Financial Modeling", "Risk Management", "SQL"],
        "recommended_subjects": ["Engineering Mathematics-III", "Engineering Mathematics-IV", "Data Structures and Algorithms", "Python Programming"],
        "recommended_electives": ["Machine Learning", "Big Data Analytics"],
        "min_cgpa_recommended": 8.0,
        "job_titles": ["Quant Analyst", "Quantitative Developer", "Algorithmic Trader", "Risk Analyst", "FinTech Engineer"],
        "salary_range": {"entry_level": "10-18 LPA", "mid_level": "20-40 LPA", "senior_level": "40-80 LPA", "top_companies": "50-2Cr+ LPA"},
        "top_companies_india": ["Zerodha", "Groww", "Angel One", "Goldman Sachs India", "Morgan Stanley India", "Tower Research India"],
        "top_companies_global": ["Jane Street", "Two Sigma", "Citadel", "DE Shaw", "Renaissance Technologies"],
        "market_demand": "HIGH",
        "growth_potential": "Very High — FinTech and algo trading growing in India",
        "certifications": ["CFA Level 1", "FRM", "QuantInsti EPAT"],
        "roadmap": [
            {"step": 1, "title": "Advanced Mathematics", "description": "Linear algebra, probability, stochastic processes, optimization", "duration": "4-6 months"},
            {"step": 2, "title": "Programming & Data", "description": "Python, NumPy, Pandas, statistical modeling, time series", "duration": "3 months"},
            {"step": 3, "title": "Financial Theory", "description": "Options pricing, portfolio theory, risk models, market microstructure", "duration": "3-4 months"},
            {"step": 4, "title": "ML for Finance", "description": "Predictive modeling, NLP for sentiment, reinforcement learning", "duration": "3 months"},
            {"step": 5, "title": "Trading Systems", "description": "Build backtesting frameworks, paper trading strategies", "duration": "Ongoing"},
        ],
        "keywords": ["quant", "quantitative", "fintech", "finance", "trading", "algorithmic", "financial", "risk", "hedge fund"],
        "related_careers": ["Data Scientist", "ML Engineer", "Data Analyst"],
    },
    # ─── 28 AI Ethics & Governance Specialist ──────────
    {
        "title": "AI Ethics & Governance Specialist",
        "category": "RESEARCH",
        "description": "Ensure AI systems are fair, transparent, and responsible. Emerging role as governments and companies adopt AI regulations. India's Digital India Act will drive demand.",
        "required_skills": ["AI/ML Fundamentals", "Ethics Frameworks", "Bias Detection", "Policy Writing", "Data Privacy (GDPR/DPDPA)", "Explainable AI", "Research", "Communication"],
        "recommended_subjects": ["Artificial Intelligence", "Software Engineering", "Engineering Mathematics-III"],
        "recommended_electives": ["Machine Learning", "Cyber Security", "Digital Ethics"],
        "min_cgpa_recommended": 7.5,
        "job_titles": ["AI Ethics Specialist", "Responsible AI Lead", "AI Governance Analyst", "AI Policy Researcher", "Fairness Engineer"],
        "salary_range": {"entry_level": "6-10 LPA", "mid_level": "12-25 LPA", "senior_level": "25-45 LPA", "top_companies": "30-60+ LPA"},
        "top_companies_india": ["Google India", "Microsoft India", "Wipro AI Ethics", "NASSCOM AI", "NITI Aayog"],
        "top_companies_global": ["Google DeepMind", "OpenAI", "Microsoft", "IBM AI Ethics", "Partnership on AI"],
        "market_demand": "EMERGING",
        "growth_potential": "Very High — AI regulation becoming mandatory worldwide",
        "certifications": ["AI Ethics (Coursera)", "Certified Information Privacy Professional (CIPP)", "Responsible AI Certification"],
        "roadmap": [
            {"step": 1, "title": "AI/ML Foundations", "description": "Understand how ML models work, common failure modes", "duration": "3 months"},
            {"step": 2, "title": "Ethics & Philosophy", "description": "Study fairness, accountability, transparency frameworks", "duration": "2-3 months"},
            {"step": 3, "title": "Bias & Fairness Tools", "description": "Fairlearn, AI Fairness 360, model interpretability (SHAP, LIME)", "duration": "2-3 months"},
            {"step": 4, "title": "Policy & Regulation", "description": "EU AI Act, India DPDPA, NIST AI Risk Framework", "duration": "3 months"},
            {"step": 5, "title": "Research & Advocacy", "description": "Publish papers, contribute to policy discussions", "duration": "Ongoing"},
        ],
        "keywords": ["ai ethics", "responsible ai", "fairness", "governance", "bias", "transparency", "policy", "regulation", "privacy"],
        "related_careers": ["AI Research Engineer", "Data Scientist", "Product Manager"],
    },
]


async def seed_careers():
    """Seed career paths into MongoDB"""
    from app.models.career import CareerPath, CareerCategory, DemandLevel, SalaryRange, RoadmapStep

    existing = await CareerPath.find().count()
    if existing > 0:
        logger.info(f"Career data already exists ({existing} records). Deleting and re-seeding...")
        await CareerPath.find().delete()

    # Convert dictionaries to CareerPath objects AFTER Beanie is initialized
    careers = []
    for data in CAREERS_DATA:
        # Convert nested objects using enum member access by NAME
        data["category"] = CareerCategory[data["category"]]  # Access by name e.g. CareerCategory["SOFTWARE_DEVELOPMENT"]
        data["market_demand"] = DemandLevel[data["market_demand"]]  # Access by name e.g. DemandLevel["VERY_HIGH"]
        data["salary_range"] = SalaryRange(**data["salary_range"])
        data["roadmap"] = [RoadmapStep(**step) for step in data["roadmap"]]
        careers.append(CareerPath(**data))

    await CareerPath.insert_many(careers)
    logger.info(f"✅ Seeded {len(careers)} career paths")
    return len(careers)


# CLI entry point
if __name__ == "__main__":
    from motor.motor_asyncio import AsyncIOMotorClient
    from beanie import init_beanie
    from app.core.config import settings
    from app.models.career import CareerPath

    async def main():
        client = AsyncIOMotorClient(settings.MONGODB_URL)
        await init_beanie(database=client[settings.MONGODB_DATABASE], document_models=[CareerPath])
        count = await seed_careers()
        print(f"Done! Seeded {count} careers.")
        client.close()

    asyncio.run(main())