from . import academic
from . import electives
from . import student_analysis
from . import resources
from . import messages
from . import students
from . import weakness
from . import analytics
from . import achievements
from . import publications
from . import research_area
from . import appointments
from . import student_projects_enhanced
